### ISSUE TITLE
tar@3.0.0 broke package wndb-with-exceptions and wordnet-db

### ISSUE THREAD

**Issue by ZaDarkSide** [npm/node-tar#109]
Packages [WNdb-with-exceptions](https://github.com/morungos/WNdb-with-exceptions) and [wordnet-db](https://github.com/moos/wordnet-db) use in their `package.json` the package `tar@latest`.
The developers didn't take into account that between `tar@2.2.1` and `tar@3.0.0` will be breaking changes.

Is there any way to force those packages to use `tar@2.2.1` instead of `tar@3.0.0` ?
I have tried to generate a valid `npm-shrinkwrap.json` but it's not working, I also opened an issue on those project trackers:

```json
{
	"dependencies": {
		"lemmer": {
			"version": "0.2.1",
			"from": "lemmer@0.2.1",
			"dependencies": {
				"wndb-with-exceptions": {
					"version": "3.0.1",
					"from": "wndb-with-exceptions@3.0.1",
					"dependencies": {
						"tar": {
							"version": "3.0.0",
							"from": "tar@2.2.1"
						}
					}
				}
			}
		},
		"wordpos": {
			"version": "1.1.2",
			"from": "wordpos@1.1.2",
			"dependencies": {
				"wordnet-db": {
					"version": "3.1.2",
					"from": "wordnet-db@3.1.2",
					"dependencies": {
						"tar": {
							"version": "3.0.0",
							"from": "tar@2.2.1"
						}
					}
				}
			}
		}
	}
}
```

**Comment by isaacs** [comment]
Since wordnet-db uses node-tar on install, there's not much to be done about it.
