### ISSUE TITLE
Needs example for tar.Pack. Does the packer even work?

### ISSUE THREAD

**Issue by coolaj86** [npm/node-tar#11]
I tried looking at what you've got in `test/pack.js`, but the test doesn't pass and I couldn't figure out how to create a simple example using `tar.Pack`.

It seems that it immediately pauses the `fstream.Reader` and then quits. Or at least I get events when I test `fstream.Reader#on('entry', fn)` by itself, but nothing once I pipe it to `pack`.

**Comment by isaacs** [comment]
Done on v3.
