### ISSUE TITLE
can't find details on v3's breaking changes

### ISSUE THREAD

**Issue by rmg** [npm/node-tar#113]
Where I looked and the order I looked in, in case it helps decide where to document it:
1. readme on npm package page
1. `CHANGES.md`/`CHANGELOG.md`/etc. in repo
1. `README.md` in repo
   1. changes/history section
   1. upgrade guide
1. GH releases
1. commit history (skimming for "breaking", "semver-major", etc.)

**Comment by rmg** [comment]
In case anyone is looking for an actual answer to the above, any references to node-tar@2/3 being "a complete rewrite" basically means that everything except the name of the package changed. The previous API was mostly "documented" only in the form of examples.

**Comment by isaacs** [comment]
Yes, really the scope of change is "the readme".  When I say "a complete rewrite", I mean, "Started from scratch, because the previous version was irredeemable."  I certainly cribbed some notes from v2, but not even that much.

**Comment by ForsakenHarmony** [comment]
Uhh where's a changelog?

**Comment by mrtnzlml** [comment]
Hi! Could you please document what changed in the latest version 5? Thank you! :)

**Comment by Hypnosphi** [comment]
Most likely it's just dropped Node 4 support https://github.com/npm/node-tar/commit/0b0a9935eb41ccc74e3a9712559936c40cd3e1bc

But I'm not sure there isn't something else

**Comment by isaacs** [comment]
Fixed f9555ddc60d5199ff92f99b2ddff7629f4c2dd35

v5 is mostly about the new error codes, the new `TAR_BAD_ARCHIVE` error/warning, and fixing a race condition in unpack.
