### ISSUE TITLE
portable archives should not include dir mtimes (maybe any mtimes?)

### ISSUE THREAD

**Issue by isaacs** [npm/node-tar#116]
If you add a file then remove it, the dir's mtime changes.

Hard to justify including dir mtimes in the archive when in portable mode.  Files makes more sense, because the `--newer` options.

**Comment by rmg** [comment]
What about a way of forcing mtimes on files to be stripped as well? It would be nice if, for example, `npm pack` of checkout of a given tag always produced the same tarball (as in same shasum) for cases where no scripts are involved.
