### ISSUE TITLE
async API truncates filename input array

### ISSUE THREAD

**Issue by elad-nach** [npm/node-tar#120]
I use the module to compress a number of files, which I would like to delete afterwards:
```
   tar.c(
        {
            gzip: true,
            file: `${Date.now()}.tgz`
        },
        filesCreated
    ).then(()=>{
    removeFilesSync(filesCreated);
   });
```

after calling the compress method - the input array is empty and cannot be used, I guess due to this [line](https://github.com/npm/node-tar/blob/master/lib/create.js#L85).

a workaround is to force `sync: true` with the options.

I believe the desirable behaviour is that the input array stays intact. Would gladly submit a pull request!

**Comment by elad-nach** [comment]
another inspection shows that this shows up in several other places in this package. any particular reason that it was designed this way?

**Comment by isaacs** [comment]
Makes it easier to go off to do an async thing, then come back to the list of files.

But yeah, it doesn't need to be mutating in place like that.  I can clone the array easily enough.  Patch coming shortly.

**Comment by elad-nach** [comment]
cheers!
