### ISSUE TITLE
pipe() chaining

### ISSUE THREAD

**Issue by soichih** [npm/node-tar#124]
Hello. 

I am reading a large tar file from somewhere and writing it locally.  I then need to list the file content just to verify what's in it.

Instead of having to re-read the entire content, I was hoping I could do this.

> readstream.pipe(tar.list()).pipe(fs.createWriteStream(path));

This results in

> TypeError: readstream.pipe(...).pipe is not a function

Can node-tar be updated to allow chaining of pipe so that I don't have to re-read the .tar file?

**Comment by isaacs** [comment]
`tar.list` doesn't output a stream.  But the good news is that you can pipe to multiple writable streams just fine.

Try this:

```js
readstream.pipe(tar.list())
readstream.pipe(fs.createWriteStream(path))
```

**Comment by soichih** [comment]
Thanks!
