### ISSUE TITLE
Entry path contains null byte at end

### ISSUE THREAD

**Issue by freitagbr** [npm/node-tar#127]
When using `node-tar` to parse a .tgz, I noticed that the value of `entry.path` had a null character at the end. Here's the object returned from `path.parse` (note that the entry in the .tgz was another .tgz):
```
{
    root: '',
    dir: 'example',
    base: 'example.tgz\u0000',
    ext: '.tgz\u0000',
    name: 'example'
}
```
However, the file does not actually have null bytes in the filename.

**Comment by freitagbr** [comment]
I did a `git bisect` and found that the issue was introduced in commit `9594f82`.

**Comment by freitagbr** [comment]
Ok, I believe I found the issue. For my particular tar, the entry before the .tgz entry is a `'NextFileHasLongPath'` entry, and the size is `105`. The code in `c83b0ef`, the commit before `9594f82`, a `BufferEntry` is created for this type of entry, and the buffer entry contains this code:
```
this.on("end", function () {
  this.body = this._buffer.toString().slice(0, -1)
})
```
The `_buffer` is `105` long, which includes the null byte at the end, but `.slice(0, -1)` removes the null byte.

However, in `9594f82`, `consumeBodyChunk` is used to parse the buffer. Nothing special is done for `'NextFileHasLongPath'`, and the buffer is sliced the following way:
```
emit(chunk.slice(0, entry.remain))
```
where `entry.remain` is `105` again. Thus, the null byte at the end is included in the path.

So, for `'NextFileHasLongPath'`, `'NextFileHasLongLinkPath'`, and `'OldGnuLongPath'`, the last byte returned from `consumeBodyChunk` should be removed.

**Comment by freitagbr** [comment]
Here is an example test case and file that has this issue (zipped for GitHub attachment rules):
[null-byte.zip](https://github.com/npm/node-tar/files/1189164/null-byte.zip)
```js
'use strict';
const fs = require('fs');
const tar = require('./');

const file = fs.createReadStream('./null-byte.tgz');
const parse = new tar.Parse();

parse.on('entry', (entry) => {
    if (entry.path.includes('\u0000')) {
        console.log('bad entry path: %j', entry.path);
        process.exitCode = 1;
    }
    entry.resume();
});

file.pipe(parse);
```

**Comment by isaacs** [comment]
9594f82 is a heck of a commit for it to be introduced in.  Investigating now.

**Comment by isaacs** [comment]
Thanks!  Turned out to be an easy fix, once identified.

**Comment by freitagbr** [comment]
Sure thing, thanks for the fix!
