### ISSUE TITLE
.Pack should have a way to use global space vs the directory prefix

### ISSUE THREAD

**Issue by bmeck** [npm/node-tar#13]
Code such as the following:

```
fstream.Reader({ path: path.join(__dirname, './xyz'), type: "Directory" })
.pipe(tar.Pack({ noProprietary: true }))
.pipe(destination)
```

Will always prefix the entries of a tar with `xyz/...` , there should be a sane way to prevent this and set a default if you want to add a custom prefix

**Comment by isaacs** [comment]
Done on v3.
