### ISSUE TITLE
3.1.9 not firing end event

### ISSUE THREAD

**Issue by evilpacket** [npm/node-tar#130]
I ran into a situation today in which I upgraded to tar 3.1.9 from 3.1.8

Example below: using the ember-source@2.15.0-beta.3 tarball (but seems to do the same for whatever tarball I pick) from the registry the 'done' is never printed. Downgrade to 3.1.8 and it works just fine. 3.1.9 does not seem to ever get the end event.

```
'use strict';

const Tar = require('tar');
const Path = require('path');
const Fs = require('fs');

const inputFile = Fs.createReadStream(process.argv[2]);
const tarStream = Tar.x({
  strip: 1,
  cwd: './out',
  strict: true,
  preserveOwner: false
});

tarStream.on('error', (err) => {
  console.log('err');
});

return inputFile.pipe(tarStream).on('end', () => {
  console.log('DONE');
});
```

**Comment by isaacs** [comment]
It was an unfortunate error to have ever emitted `'end'` for tar.x, since that is a writable stream, not a readable stream.

The event you want is `close`, which indicates that all files have been extracted, written to disk, chmoded and chowned as appropriate, and their file descriptors closed.

**Comment by evilpacket** [comment]
Oh! Thank you for the clarification.
