### ISSUE TITLE
cwd is not treated as documented

### ISSUE THREAD

**Issue by gabrielcsapo** [npm/node-tar#136]
when running the following code:

```
tar.create({
      gzip: true,
      portable: true,
      file: 'bundle.tgz',
      cwd: directory
}, fs.readdirSync(directory));
```

it will output `bundle.tgz` to the process.cwd() directory, which is not the specified directory.

When running the following code:

```
tar.create({
      gzip: true,
      portable: true,
      file: directory + '/bundle.tgz'
}, fs.readdirSync(directory));
```

it works as expected and outputs the bundle to the correct directory. Is this intended behavior?

**Comment by gabrielcsapo** [comment]
Just read through and saw this test https://github.com/npm/node-tar/blob/c234df13010a540b90c1b72efa96f164f700a21a/test/create.js#L59, so the cwd directory is not used as an absolute path if otherwise stated? The file will always be created in the process.cwd()?

**Comment by isaacs** [comment]
The cwd is like `tar(1)`'s `-C` option.  It is the directory that the things you're packing live in.  It's not the directory where the output tarball will be created.

For example, if you have a file at `x/y/foo` and you do:

```
tar cf foo.tar -C x y/foo
```

then you'll get a file at `./foo.tar` with a single entry in it, with the entry path `y/foo`.

This is working as intended.  Sorry for the confusion.  I'd accept a doc patch to clarify this behavior.
