### ISSUE TITLE
No error for attempting to extract a non-tar file?

### ISSUE THREAD

**Issue by dennismckinnon** [npm/node-tar#137]
Hello,

I have been working with this lib for a couple days and I have noticed that there doesn't seem to be any error thrown by either the extraction or listing functions when passed a file or stream which is not actually a tar file.

Since you are emulating the functionality of the command line tar which does throw an error in these circumstances i assume this is an oversight? If not can it be a feature request? I am going to have to do input validation on the contents of the archive anyways but being sure that i at least received a tar file would make things easier for me.

Thanks

Output of command line tar when passed non-tar file

```
$ tar -xf spec.json
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

**Comment by isaacs** [comment]
It does emit a warning when it gets a corrupted block.  The best way to catch that warning this would be to add a `onwarn` function in the options.

It looks like bsdtar is doing that "does not look like a tar archive" warning when the file does not have any non-corrupted entries.  Could definitely detect that easily enough, but yes, it's a feature request.

**Comment by DanielSWolf** [comment]
👍 
It would be great if I could distinguish whether a tarball is valid but empty, or simply corrupt.

**Comment by isaacs** [comment]
But an empty file is a valid tarball!

```
$ touch empty-file
$ tar tf empty-file
$ echo $?
0
```

If the file is _not_ empty, but does not have any valid entries, then it should emit a warning.

Tar v5 detects this situation and does the right thing now.  See [Warnings and Errors](https://github.com/npm/node-tar#warnings-and-errors), specifically the `TAR_BAD_ARCHIVE` error code.
