### ISSUE TITLE
Buffer.alloc is not a function

### ISSUE THREAD

**Issue by pepone** [npm/node-tar#139]
Buffer.alloc used in lib/pack.js was introduced in v5.10.0, but package.json states it is compatible with node >=4.5

**Comment by shinnn** [comment]
[`Buffer.alloc` has been backported to Node.js v4.5.0](https://github.com/nodejs/node/commit/34776ec92065abf53240638df8763e309322938e). The package.json of this library is correct.

**Comment by pepone** [comment]
@shinnn  cool thanks, the docs didn't mention this backport

**Comment by shinnn** [comment]
https://nodejs.org/docs/v8.4.0/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding

> Added in: v5.10.0

Yes, I think it should mention the backport, too.
