### ISSUE TITLE
Should tar.extract with cwd: create folders if necessary?

### ISSUE THREAD

**Issue by ilg-ul** [npm/node-tar#141]
When I updated an older project from 2.x to 4.x I noticed that not only I had to update from `tar.Extract({ path: destPath })` to `tar.extract({ cwd: destPath })`, but I also had to manually `mkdirp(destPath)` before.

Is this behaviour (not automatically creating the destination folder) intentional? I noticed some issues related to `chmod`, but I'm not sure they prevent creating the destination folder.

**Comment by isaacs** [comment]
Currently, no, it does not do that, and yes that is intentional.  It now follows the behavior of command-line tar with the `-C <path>` option.

I'd be open to adding a `createCwd` boolean option or something.

**Comment by ilg-ul** [comment]
> I'd be open to adding a createCwd boolean option

+1
