### ISSUE TITLE
How to use stream as file 

### ISSUE THREAD

**Issue by lichenhao** [npm/node-tar#143]
I have some file stream and I hope to use tar.Extract to pack those file to a `tar.gz` file ?
I read the code if I use this for now, I must create some folder or files and then use this to pack them in.

How about use stream instead?

**Comment by lichenhao** [comment]
How about supported memory-fs ?

**Comment by isaacs** [comment]
When you say `tar.Extract`, do you mean `tar.Pack()`?  (`tar.Extract` isn't a thing.)

The problem with using a stream is that it doesn't have the stat information required to build up the archive header.  (Entry type, filename, modes, owner, ctime, mtime, size, etc.)

You can do this by digging into some of tar's internals, though.  They're supported and documented.

```js
const fs = require('fs')
const tar = require('tar')
// we have to know the size up front
const size = 123
// the block size is the size rounded up to the nearest 512
const blockSize = Math.ceil(size / 512) * 512
// have to pad with zeroes up to the block boundary
const pad = Buffer.alloc(blockSize - size)
// create the packer
const p = new tar.Pack()
// pipe it to a file, I guess?  Or wherever it's going
p.pipe(fs.createWriteStream('output.tar'))
// create the header
const h = new tar.Header({
  path: 'some-file.txt',
  mode: 0o0644,
  size: size,
  type: 'File',
  mtime: new Date(),
  uid: process.getuid(),
  gid: process.getgid(),
  uname: process.env.USER,
  gname: process.env.GROUP
})
// create the ReadEntry, so it works as if we're slurping in entries from another archive
const re = new tar.ReadEntry(h)

// add the read entry to the packer
p.write(re)

// write the data
// this could be a stream or whatever
re.write(Buffer.allocUnsafe(size))

// pad out to the block boundary when that's done
re.end(pad)
re.end()

// after you've written all your entries, end the packer
p.end()
```

**Comment by lichenhao** [comment]
Thank you but I found the package named tar-stream and I fixed this question with it.
