### ISSUE TITLE
test/cb-never-called-1.0.1.tgz failes in virus scans, and appears to be corrupt

### ISSUE THREAD

**Issue by pegues** [npm/node-tar#150]
Please fix the file test/cb-never-called-1.0.1.tgz When ran through a virus scan, the scanner crashes due to the tgz file being corrupt.

Other posts in which people are referring to this file are:

https://github.com/angular/angular-cli/issues/4161
https://github.com/npm/npm/issues/7014

**Comment by isaacs** [comment]
Fixed in #155, somewhat incidentally.
