### ISSUE TITLE
strip with negative value

### ISSUE THREAD

**Issue by bhaktakg** [npm/node-tar#159]
I really need to extract the files from a tar file into a single folder (the tar file may contain folders and I do not want to these created). 

I took the liberty of modifying "unpack.js" as follows and looks like it does work:

```js
  [CHECKPATH] (entry) {
    if (this.strip) {
      const parts = entry.path.split(/\/|\\/)
      if (this.strip > 0){
        if (parts.length < this.strip)
          return false
        entry.path = parts.slice(this.strip).join('/')      	
      } else {
      	entry.path = path.basename(entry.path)
      }
    }
```

Let me know if there are any issues with having this option as part of your package.

**Comment by isaacs** [comment]
Wait, so, passing `strip: -1` would strip _all_ folders and only extract entries to their basename?

That seems kind of weird.  Why not just add an `onentry` that modifies the path?  You could do that by putting this in the config options:

```js
tar.x({
  onentry: e => e.path = path.basename(e.path)
})
```

**Comment by bhaktakg** [comment]
That works perfectly. Thanks. Marking it closed.
