### ISSUE TITLE
Error: process.binding is not supported

### ISSUE THREAD

**Issue by Hertox82** [npm/node-tar#161]
Hi,
i have this error when try to compress some folder.

This is my configuration:

main.ts
```typescript
import { create } from 'tar';
import * as path from 'path'; 


const folderPath = path.resolve(__dirname+'/../dist');
create({
    gzip: true,
    file: 'ptar.tgz'
},[
    folderPath
]);
```
Some idea to resolve it?

thank you in advance

**Comment by Hertox82** [comment]
the name of process.binding that throw this error is zlib

**Comment by isaacs** [comment]
I think this is a typescript error.  Works fine in JavaScript.  Typescript isn't allowing you to call into process.binding, it looks like.

**Comment by Hertox82** [comment]
I found solution for this issue:
in webpack.config.js put this
```javascript
module.exports = {
   /* other options*/
    target: 'node',
    node: {
        fs: 'empty'
    }
/* ... */
}
```

**Comment by Hertox82** [comment]
> I think this is a typescript error. Works fine in JavaScript. Typescript isn't allowing you to call into process.binding, it looks like.

No, the library work so well also with Typescript. This is my package [lt-pm](https://github.com/Hertox82/lt-pm) and all work fine! thanks for your reply!
