### ISSUE TITLE
Callback for tar.x()

### ISSUE THREAD

**Issue by ohpyupi** [npm/node-tar#162]
The document says that tar.x() accepts three arguments, options, filelist, and callback.
However, the callback doesn't work and raises a error that crashes the script.
And I cannot find any other callback functions that will be attached to the options object other than onentry or onwarn.

Is it just not possible to invoke callback at the end of the task? Or am I missing something on the documentation? I will really appreciate if somebody knows the solution and share with me. Thanks!

**Comment by isaacs** [comment]
This works for me:

```js
tar.x({
  file: file
}, [], (er) => {
  if (er)
    throw er
  else
    console.log('done!')
})
```

What error are you getting?  It probably says what's wrong with what you're doing.

**Comment by ohpyupi** [comment]
I got an error with this use case below
```
stream
  .pipe(tar.x(
     cwd: "path/where/a-file-will-be-extracted",
     () => {}
  ));
```
Is this a valid one to use callback?
