### ISSUE TITLE
intercept and mutate file contents during extraction

### ISSUE THREAD

**Issue by isaacs** [npm/node-tar#165]
Add a hook to do some thing in the `onentry` or some such.  Maybe let the Parser `onentry` function return a different stream and then use that piping to the file instead?

**Comment by isaacs** [comment]
Landed in 4.3.0.

Provide a `transform: (entry) => stream|falsey` method, and it'll use the data from the provided stream instead of the tar entry.

cc: @zkat

**Comment by zkat** [comment]
#blessed 🙌 😭
