### ISSUE TITLE
npm release contains vi swap file

### ISSUE THREAD

**Issue by das-schaf** [npm/node-tar#166]
'npm install tar' lists a '.parse.js.swp' within the lib folder. This file causes a warning when building a snap.

**Comment by isaacs** [comment]
which version?  I don't see that.

**Comment by das-schaf** [comment]
It's version 4.2.0.

`npm install tar@4.2.0`

`-rw-rw-r-- 1 mt mt  2374 Nov 28 02:06 create.js
-rw-rw-r-- 1 mt mt  2824 Dez 21 04:46 extract.js
-rw-rw-r-- 1 mt mt  8483 Aug 17 00:42 header.js
-rw-rw-r-- 1 mt mt   772 Mai 10  2017 high-level-opt.js
-rw-rw-r-- 1 mt mt  1978 Mai 10  2017 large-numbers.js
-rw-rw-r-- 1 mt mt  3113 Nov 28 02:06 list.js
-rw-rw-r-- 1 mt mt  5205 Dez 21 05:00 mkdir.js
-rw-rw-r-- 1 mt mt  9514 Nov 28 02:06 pack.js
-rw-rw-r-- 1 mt mt 11990 Dez 21 05:04 parse.js
-rw-rw-r-- 1 mt mt 28672 Dez 21 05:05 .parse.js.swp <----
-rw-rw-r-- 1 mt mt  4032 Aug 17 00:42 pax.js
-rw-rw-r-- 1 mt mt  2467 Sep 17 21:55 read-entry.js
-rw-rw-r-- 1 mt mt  5454 Nov 28 02:06 replace.js
-rw-rw-r-- 1 mt mt  1095 Mai 11  2017 types.js
-rw-rw-r-- 1 mt mt 13380 Dez 20 23:42 unpack.js
-rw-rw-r-- 1 mt mt   852 Aug 21 03:05 update.js
-rw-rw-r-- 1 mt mt   309 Aug 21 03:04 warn-mixin.js
-rw-rw-r-- 1 mt mt   533 Aug 21 03:04 winchars.js
-rw-rw-r-- 1 mt mt 11469 Nov 28 02:06 write-entry.js`

in version 4.3.0

`-rw-rw-r-- 1 mt mt  2374 Nov 28 02:06 create.js
-rw-rw-r-- 1 mt mt  2824 Dez 21 04:46 extract.js
-rw-rw-r-- 1 mt mt  8479 Dez 21 05:41 header.js
-rw-rw-r-- 1 mt mt   772 Mai 10  2017 high-level-opt.js
-rw-rw-r-- 1 mt mt  1978 Mai 10  2017 large-numbers.js
-rw-rw-r-- 1 mt mt  3113 Nov 28 02:06 list.js
-rw-rw-r-- 1 mt mt  5180 Dez 21 06:06 mkdir.js
-rw-rw-r-- 1 mt mt  9514 Nov 28 02:06 pack.js
-rw-rw-r-- 1 mt mt 11990 Jan 18 01:29 parse.js
-rw-rw-r-- 1 mt mt  4032 Aug 17 00:42 pax.js
-rw-rw-r-- 1 mt mt  2467 Sep 17 21:55 read-entry.js
-rw-rw-r-- 1 mt mt  5454 Nov 28 02:06 replace.js
-rw-rw-r-- 1 mt mt  1095 Mai 11  2017 types.js
-rw-rw-r-- 1 mt mt 13677 Jan 18 01:53 unpack.js
-rw-rw-r-- 1 mt mt 28672 Jan 18 01:53 .unpack.js.swp <----
-rw-rw-r-- 1 mt mt   852 Aug 21 03:05 update.js
-rw-rw-r-- 1 mt mt   309 Aug 21 03:04 warn-mixin.js
-rw-rw-r-- 1 mt mt   533 Aug 21 03:04 winchars.js
-rw-rw-r-- 1 mt mt 11469 Nov 28 02:06 write-entry.js`

using npm 3.10.10 on ubuntu lts 16.04

**Comment by diddledan** [comment]
in version 4.4.13 there is a `./lib/.mkdir.js.swp`

This appears to be a common occurrance for this module. Perhaps the releases should be built from a clean tree each time rather than an existing developer's copy to avoid this recurring?
