### ISSUE TITLE
Memory issues with sync version of tar.create 

### ISSUE THREAD

**Issue by tgds** [npm/node-tar#170]
I know that minipass is designed to buffer data until 'data' event handler is added, so you don't loose the first chunk. However, in the sync version of tar.create, the event handler is added after the whole file is read and buffered in memory. This can bring the entire machine to a halt if a large file is encountered.

**Comment by tgds** [comment]
There's a similar issue in the async version. I did observe big memory spikes when a large file was encountered. My hypothesis is that this happens when write is much slower than read and the buffer grows too large over time.

**Comment by isaacs** [comment]
/shrug Use the async version, or have you tried to reduce the maxReadSize option from its default of 16MB?
