### ISSUE TITLE
is it possible to create tar.gz with a flat structure

### ISSUE THREAD

**Issue by bhaktakg** [npm/node-tar#172]
I would like to create a tar.gz file whose contents come from various sub folders. I would like the tar file to only contains the file names and not the folder structure that they come from.
Is it possible to do this. I had a look at the various options and could not file one where the paths are stripped.

**Comment by bhaktakg** [comment]
Not required anymore

**Comment by cannonmike92** [comment]
I'd really like to have this feature as well, if at all possible.
