### ISSUE TITLE
In transform, doing entry.on("data") cause output files to be zero size

### ISSUE THREAD

**Issue by jchip** [npm/node-tar#173]
When extracting, I want to tap into the output stream of each entry and do something like calculating checksum.  I tried adding a transform that add an `entry.on("data")` listener and pump the data into a crypto hasher.  However, I found that just the presence of that listener, even if the handler is noop, it cause the output files to be zero size.

OS: Mac High Sierra 10.13.3
node version: 8.9.4
node-tar version: 4.3.3

Some observations:

- it appears that the extract is not resolving the promise or invoking the callback.
- sync extract by setting the `sync` flag everything works as expected

Here is a sample that demo the issue.

```js
const Path = require("path");
const Tar = require("tar");
const fs = require("fs");
const assert = require("assert");

const tmpFile = "tmp.tgz";
const tmpOutDir = Path.resolve("tmpout");
const helloFile = "hello.txt";

try {
  fs.mkdirSync(tmpOutDir);
} catch (e) {
  if (e.code !== "EEXIST") {
    console.log(e);
    process.exit(1);
  }
}

fs.writeFileSync(helloFile, "hello world\n");

Tar.c(
  {
    file: tmpFile
  },
  [helloFile]
)
  .then(() => {
    return Tar.x({
      cwd: tmpOutDir,
      file: tmpFile,
      transform: entry => {
        entry.on("data", () => {
          console.log("on data");
        });
      }
    });
  })
  .then(() => {
    const readback = fs.readFileSync(Path.join(tmpOutDir, helloFile)).toString();
    assert(readback.length > 0, `unexpected file size ${readback.length}`);
    console.log("done", readback);
  });
```

**Comment by isaacs** [comment]
Yeah, you're consuming _all_ of the data before the data can be written to a file.  (Usually, it's all in memory, so your handler is just slurping it in right away.)

You can do this by using the `transform` option, and returning a passthrough stream that you pipe the data into before attaching your handler.

```js
const Minipass = require('minipass')
tar.x({
  cwd: tmpOutDir,
  file: tmpFile,
  transform: entry => {
    const ret = new Minipass()
    entry.pipe(ret)
    entry.on('data', chunk => console.log('whatever', chunk.length))
    return ret
  }
})
```

I know this is a bit of a pita, I'm sorry.  This library is optimized for speed and power, so there are a few edge cases that can be a little sharp.

**Comment by jchip** [comment]
thank you.  that works.  I am happy with the solution.  I tried the same thing but returned entry rather than the new Minipass instance.  Silly.  :)

I'd love to add a simple sample for this in the README.
