### ISSUE TITLE
directories in tar files created on windows do not have the -x permission

### ISSUE THREAD

**Issue by matthewdolman** [npm/node-tar#178]
When I create a tar file in windows

```
return tar.create(
        {
            file: "file.tar",
        },
        [files]
)
```

The folder inside the archives have the permissions rw-rw-rw-

This means that when I come to extract the archive on a windows machine the subdirectories inside /files/ are not accessible to have their contents written to them.

Is there a way to avoid this?

**Comment by scottasmith** [comment]
I am also facing this issue

**Comment by andyATryonsoft** [comment]
I'm having the same problem.  Any eta on this issue?

**Comment by isaacs** [comment]
e89c4d37519b1c20133a9f49d5f6b85fa34c203b fixes this issue.
