### ISSUE TITLE
Acorn error: Invalid Number

### ISSUE THREAD

**Issue by jeroldhaas** [npm/node-tar#185]
...building with `nexe` - a library includes `tar`

```
Acorn error: Invalid number (108:10)
File: /home/user/Documents/tessr-labs/gitlab/tessr-batch-transaction/node_modules/tar/tar.js

106  // values for the mode field
107  var modes =
108    { suid: 04000 // set uid on extraction <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
109    , sgid: 02000 // set gid on extraction
110    , svtx: 01000 // set restricted deletion flag on dirs on extraction
111    , uread:  0400
112    , uwrite: 0200

```

**Comment by jeroldhaas** [comment]
...building with `nexe` - a library includes `tar`

**Comment by s1na** [comment]
I have the same problem when rollup tries to build tar as a dep of a dep. As a quick workaround I'm using `rollup-plugin-re` with the following config:

```javascript
plugins: [
  re({
    patterns: [
      {
         include: 'node_modules/tar/**',
         test: /\s0\d+/g,
         replace: function (it) { return ' parseInt("' + it.trim() + '", 8)'; }
       }
    ]
  })
]

**Comment by jeroldhaas** [comment]
If I better knew the nature of this build error I'd PR the `tar` project with the necessary changes. There was a similar problem with another filesystem-related project, I'd seen, and a PR managed to fix it.

If any contributors that know the nature of that fix can chime in, I'd be happy to assist in solving this issue with `tar` and possibly other libraries with similar issues.
