### ISSUE TITLE
this is not a typed array

### ISSUE THREAD

**Issue by zhoukekestar** [npm/node-tar#186]
Code in `lib/parse.js:#33` occurs error.

```bash
➜  temp node
>  Buffer.from([0x1f, 0x8b])
TypeError: this is not a typed array.
    at Function.from (native)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
>
>
>
>
(To exit, press ^C again or type .exit)
>
➜  temp node -v
v5.6.0
➜  temp
```

But this lib declares that it supports `node >= 4.5`, which is not matched. 
https://github.com/npm/node-tar/blob/HEAD/package.json#L39

**Comment by addaleax** [comment]
Node.js 5 has been unsupported since 2 years, and has a number of known severe security issues – *please* upgrade to a supported version.

Node.js 4 is also unsupported, but only since April of this year.

You can find more information about the different release lines here: https://github.com/nodejs/Release#release-schedule

**Comment by zhoukekestar** [comment]
Got it. Thanks for your information. Update the field `engines` in `package.json` will be more friendly for the other developers.  🙃

**Comment by BHare1985** [comment]
This looks like it can be accommodated by adding `const Buffer = require('./buffer.js')` to parse.js

I would second the notion of updating engines. In fact, as I understand it, version 4  dropped/broke support for node.js 4/5  and when it done so it should of updated it's major version.

There are many popular plugins that rely on tar: ^4  that don't know node.js 4/5 isn't supported.
