### ISSUE TITLE
FD is not closed in case Pack fails

### ISSUE THREAD

**Issue by tgds** [npm/node-tar#196]
_lib/create.js Line54_:

```javascript
  const promise = new Promise((res, rej) => {
    stream.on('error', rej)
    stream.on('close', res)
    p.on('error', rej)
  })
```

If Pack fails, the promise is rejected, but the writable stream stays open and file descriptor is not released properly. Subsequently, if you want to delete the .tar file when _tar.c_ fails in your app, you will run into EPERM errors. 

Not very elegant, but something like this should do(?):
```javascript
  const promise = new Promise((res, rej) => {
    let pErr = null
    stream.on('error', rej)
    stream.on('close', () => {
      if (pErr) { rej(pErr) }
      else { res() }
    })
    p.on('error', (e) => {
      if (!pErr) { // some more errors might be emitted further, we don't care about those
        pErr = e
        stream.end()
      }
    })
  })
```

Edit:
Actually, there's still a bug above. Pack can still do a couple of writes after the error event is emitted. If that happens before the stream 'close' event is emitted, it will cause stream to emit 'Write after End' error and we will reject with that instead of the original Pack error. 
It gets kinda ugly:
```javascript
  const promise = new Promise((res, rej) => {
    let pErr = null
    stream.on('error', (e) => {
      if(pErr) { rej(pErr) }
      else { rej(e) }
    })
    stream.on('close', () => {
      if (pErr) { rej(pErr) }
      else { res() }
    })
    p.on('error', (e) => {
      if (!pErr) { // some more errors might be emitted further, we don't care about those
        pErr = e
        stream.end()
      }
    })
  })
```

**Comment by isaacs** [comment]
Do you have an example showing this behavior?  The `fs-minipass` module [automatically closes before emitting an 'error' event](https://github.com/npm/fs-minipass/blob/master/index.js#L230-L234), so the additional check _should_ be unnecessary.
