### ISSUE TITLE
Not Following Symlink CWD

### ISSUE THREAD

**Issue by jvanalst** [npm/node-tar#204]
Hi,

I don't know if this is intended or not, but it's causing my issues because on Mac OS /tmp is a symbolic link to /private/tmp. On most Unix-y OSs and in AWS Lambdas it is just a regular directory.

The problem comes from mkdir.js:72, or thereabouts where the check for a directory does an ```fs.lstat``` (which treats a symlink as a file) instead of an ```fs.stat``` (which treats it as a directory). 

Just wondering if there's a good reason for preferring lstat to stat? Just curious really, since it's mildly inconvenient (yes I know I should probably use ```os.tmpdir()```).

**Comment by stkb** [comment]
I've run into the same problem when using `npm link` with a package that downloads a binary straight into its own directory (which is a symlink because of npm link). Have created #214 to fix it.
