### ISSUE TITLE
Callback not supported when streaming

### ISSUE THREAD

**Issue by kaneda** [npm/node-tar#206]
I see that this has already been mentioned (but closed without comment) in https://github.com/npm/node-tar/issues/162

It would be great if when passed a stream we could have a callback for completion of extraction as well.

**Comment by roman-io** [comment]
+1, a callback for completion and errors.

**Comment by isaacs** [comment]
You can do it this way, using the normal stream interface for detecting when it's done:

```js
input.pipe(tar.x()).on('close', () => console.log('it is done!'))
```

Is that sufficient, or am I missing something?
