### ISSUE TITLE
Can't extract .tar.xz

### ISSUE THREAD

**Issue by lefuturiste** [npm/node-tar#207]
I want to extract/uncompress all the files of a tar.xz archive to a folder using this code:

```
const tar = require('tar')

tar.extract({
	file: 'to_extract.tar.xz'
}, ['output'], (e) => {
	console.log(e)
})
```
I got a undefined response in the callback and nothing new in my directory.

**Comment by isaacs** [comment]
`xz` compression is not supported, sorry.  You'll have to decompress it and then extract the raw `tar`.  Only gzip compression is built in, because Node.js provides native bindings to the zlib library.
