### ISSUE TITLE
On Windows, folders are not extracted properly if cwd contains non-latin characters

### ISSUE THREAD

**Issue by bvachon** [npm/node-tar#209]
The below test shows the problem. Setting options.preservePaths allows to work around the problem.
```js
    const fse = require('fs-extra')
    const tar = require('tar')
    const tmp = require('tmp')

    it('should extract tarball content', async () => {
      // File obtained from http://registry.npmjs.org/tar/-/tar-4.4.4.tgz
      const tarballPath = 'tar-4.4.4.tgz'
      const targetFolder = path.join(tmp.dirSync().name, 'İİİİİİİİİ/tar')
      fse.ensureDirSync(targetFolder)

      await tar.extract({
        cwd: targetFolder,
        file: tarballPath,
        strip: 1,
        // preservePaths: true,
      })

      expect(fse.existsSync(path.join(targetFolder, 'lib/buffer.js'))).to.be.true
    })
```

**Comment by monoblaine** [comment]
Thank you so much for the workaround @bvachon! Without this workaround, it is impossible to install any npm package when the path to the project dir contains the <kbd>İ</kbd> character.

**Comment by monoblaine** [comment]
The root of the problem seems to be https://github.com/nodejs/node/issues/27534. (I have a PR that fixes that issue.) The problem I've stated (not being able to install any npm packages under e.g. `C:\İİİİ\`) is also fixed when that patch is applied.

**Comment by monoblaine** [comment]
The root of the problem seems to be https://github.com/nodejs/node/issues/27534. (I have a PR that fixes that issue.) The problem I've stated (not being able to install any npm packages under e.g. `C:\İİİİ\`) is also fixed when that patch is applied.

**Comment by isaacs** [comment]
It seems like this is a Node error, and trying to work around it in node-tar (eg, by using something other than the built-in `path` functions) would be unsafe.  And, if you're ok with the un-safety, you can work around it yourself by setting `preservePaths: true`.

I think we can close this then?  If not, lmk, and I'll reopen.
