### ISSUE TITLE
Files not listed when using tar.list but only when created with node-tar

### ISSUE THREAD

**Issue by uvbeenzaned** [npm/node-tar#218]
node-tar seems to have no problems listing files in a tar created by tar, 7zip, or Archive Roller but when I try to list the tar archive made by node-tar itself, it only lists top level directories for some reason. Is it me doing something wrong or is there a problem? This should be reproducible I would think just by creating an archive with node-tar and then listing it. I have done it several times without success and with several different versions.

Using this code to create the archive:
```javascript
const fs = require("fs");
const path = require("path");
const tar = require("tar");
const Util = require("./util");

const workingDir = "/etc/opt/";
const paths = ["dir1/", "dir2/", "dir3/", "dir4/"];

module.exports = class Config {
  static export(exportPath) {
    const existingPaths = paths.filter(p =>
      fs.existsSync(path.join(workingDir, p))
    );
    if (existingPaths.length !== 0) {
      tar
        .c(
          {
            gzip: true,
            sync: true,
            cwd: workingDir
          },
          existingPaths
        )
        .pipe(fs.createWriteStream(exportPath));
    } else {
      throw "Error: No configuration to export.";
    }
  }

  static genFileName() {
    return `config_export_${Util.getTimeStamp()}.tar.gz`;
  }
};
```

Using this code to list files:
```javascript
const tar = require("tar");

const paths = ["/tmp/config_export_201906211914.tar.gz"];

tar.t({
  file: paths[0],
  onentry: entry => console.log(entry.path)
});
```
The library outputs:
```
dir1/
dir2/
dir3/
dir4/
```
While tar tf <archive> outputs:
```
dir1/
dir1/settings.json
dir1/prefs.json
dir2/
dir2/stuff.xml
dir2/otherstuff.xml
dir3/
dir3/config
dir4/
dir4/config
```

**Comment by uvbeenzaned** [comment]
I just found out that behaves the same way when performing the equivalent to `tar xf`. It cannot extract the files from an archive that it has created, only the top level folders.

**Comment by isaacs** [comment]
Not sure why you'd be seeing that.  This works for me: https://gist.github.com/isaacs/0a29c789e050aa1ac35a8d952163df48

Can you try this test script, and share the output that you get?

What version of node-tar are you using?

**Comment by uvbeenzaned** [comment]
It worked, I got the correct output.
```
dir1/
dir1/prefs.json
dir1/settings.json
dir2/
dir2/otherstuff.xml
dir2/stuff.xml
dir3/
dir3/config
dir4/
dir4/config
```

This is certainly strange. I will see if I can poke around my code today to try to find anything odd that might be causing my issue.

`yarn info tar version` outputs:
```
yarn info v1.16.0
4.4.10
Done in 0.34s.
```
