### ISSUE TITLE
tar.Extract hangs on large files

### ISSUE THREAD

**Issue by Bartvds** [npm/node-tar#22]
When using the `extracter.js` example as-is with `tar.Extract` on a large (~100mb) tar file (with plenty subfolders, small and large files) the extraction sometimes stops and the application hangs waiting for events that never come. 

When I check the same tar with `tar.Parse` and log everything I see all the content entries and then the pipes finish as expected.

If I add some log handlers to the `tar.Extract` pipes I see it usually hangs on the larger files. With a bit of googling and browsing implementers I see mentions that if the file writer pauses the pipe node-tar also stops and won't emit new events.

I looked into some of the modules that use `node-tar` and they either use way more complicated code (like in npm) or reimplement the extraction based on `tar.Parse` and just buffer everything in memory.

An example tar that does this consistently on my workstation is the one in [this .tar.bz2 archive](http://download.slimerjs.org/v0.8/slimerjs-0.8-mac.tar.bz2) (both the .bz2 as .tar work fine with plain cli tar + bunzip2). It usually hangs after reaching that 80mb file.

**Comment by poddars** [comment]
I am facing the same issue when untarring the file of size 2.44GB (contains 5 files). Using the extracter.js example, it untars successfully into a file of size 74kb with no error. Another issue was, instead of untarring into folder, it extracts the contents into a file. Why would it extract the contents to a file?

**Comment by isaacs** [comment]
Works on v3 now.
