### ISSUE TITLE
Extra .tgz file when compress over the cwd path

### ISSUE THREAD

**Issue by Lzok** [npm/node-tar#220]
Hello, how are you?
I'm facing a little "problem" with my compression code. My case is I have a folder lets say `tmp/` with some files inside `file1.properties, file2.properties` and so on.
What I want is simply to compress all these files, it is working fine but in the pack, there is also an extra .tgz file (and it is empty). 
Here's a screenshot of the resulting files:
<img width="199" alt="Screen Shot 2019-07-02 at 09 22 30" src="https://user-images.githubusercontent.com/45211582/60512490-10666f00-9cab-11e9-9af0-cf49aa9b17dc.png">

`BOCM.tgz` is the file I downloaded from my service, but inside there's also another (empty) .tgz file (App Test.tgz), I don't want it to be there, I just want the property files.
One important note is that I am writing the files in a new folder every time I execute the service, so the empty .tgz file does not exist until I execute the compression code.

Here's my code:
```javascript
  await tar.c(
      {
        gzip: true,
        file: `${pathFiles}/${appName}.tgz`,
        portable: true,
        cwd: pathFiles,
      },
      ['.'],
    );
```

I'm glad to answer if you have questions! Thanks in advance.

**Edit July 15:**
My current workaround is to use the `filter` option to the `tar.c` function, like this:
```javascript
  await tar.c(
      {
        gzip: true,
        file: `${pathFiles}/${appName}.tgz`,
        portable: true,
        cwd: pathFiles,
        filter: pathFile => `${pathFile.split('/')[1]}` !== `${appName}.tgz`,
      },
      ['.'],
    );
```

It has not performance issues because we won't have more than 20 files but I don't like that so much.

**Comment by isaacs** [comment]
```js
  await tar.c(
      {
        gzip: true,
        file: `${pathFiles}/${appName}.tgz`,
        portable: true,
        cwd: pathFiles,
      },
      ['.'],
    );
```

Here's what I think is happening:

1. You're using `pathFiles` as the current working directory for listing files, and adding `.` (ie, `pathFiles`.)
2. You're _also_ putting the output file in `pathFiles`.
3. The output file is opened and created (but not written to, apparently) when the file list is generated.
4. Thus, the tarball includes an empty copy of itself.

You have two solutions.

1. Use a filter (like you're doing).
2. Put the output file somewhere other than the input folder.

As far as I can tell, this is a weird edge case, but tar is behaving appropriately, given the inputs its receiving.
