### ISSUE TITLE
Tar List in Memory

### ISSUE THREAD

**Issue by Californian** [npm/node-tar#226]
This might be more suited for e.g. StackOverflow, but I think a little more documentation here could help (and there's a tiny chance this is actually a bug) so I figured I'd open an issue; feel free to send me back to Q&A land if that's appropriate.

`tar.t`  is pretty confusing to me because I'm not very familiar with the specifics of how  `streams`  work. I thought I had sufficient understanding, but it looks like I'm missing something.

My impression is that I can create a read stream (let's call it  `fileReadStream`), use  `tar.t`  without the  `file`  argument to create a write stream (`tarWriteStream`), then  `pipe`  from  `fileReadStream`  to  `tarWriteStream`  and be on my merry way trying to figure out the callbacks and how to make that part compatible with async/await.

Unfortunately, it seems as though  `tar.t`  without the  `file`  option never actually returns. I tried adding an  `await`  beforehand, despite not thinking that was the correct approach, and it in fact did not help.

I have tried to write the readable stream to a file and that succeeded, so the read side isn't the problem.

Does  `tar.t`  actually create a writeable stream as it says in the documentation? Is there something else that needs to be done before it can be piped to?

Thank you for any help.

**Comment by isaacs** [comment]
Yes, `tar.t` returns a Writable Stream if you don't specify a file argument.  You write tar data _into_ that stream.  The data can come from anywhere.  (A tarball on disk, an http request, copied and pasted into a buffer in your code, etc.)

Here's an example that will probably help:

```
$ mkdir -p foo

$ touch foo/{a,b,c,d,e,f,g}

$ tar cvf foo.tar foo
a foo
a foo/g
a foo/a
a foo/f
a foo/c
a foo/d
a foo/e
a foo/b

$ cat t.js
const tar = require('./')
const fs = require('fs')
const readableStreamOfTarData = fs.createReadStream('foo.tar')
const tarListWriteStream = tar.t({
  onentry (entry) {
    console.error('got an entry!', entry.path)
  }
})

console.error('tarListWriteStream is a', tarListWriteStream.constructor.name)
console.error('tarListStream.writable =', tarListWriteStream.writable)
console.error('tarListStream.readable =', tarListWriteStream.readable)
console.error('tarListStream.write is a', typeof tarListWriteStream.write)
console.error('tarListStream.end is a', typeof tarListWriteStream.end)

readableStreamOfTarData.pipe(tarListWriteStream)

$ node t.js
tarListWriteStream is a Parser
tarListStream.writable = true
tarListStream.readable = false
tarListStream.write is a function
tarListStream.end is a function
got an entry! foo/
got an entry! foo/g
got an entry! foo/a
got an entry! foo/f
got an entry! foo/c
got an entry! foo/d
got an entry! foo/e
got an entry! foo/b
```

**Comment by isaacs** [comment]
Perhaps you could share some code that you think should work, but isn't working.  Because what you describe is (afaict) what I wrote above, and as you can see from the output, it works as you seem to expect.  So what's different?

**Comment by Californian** [comment]
Apologies, this was, as I suspected, due to a lack of familiarity with streams in general on my part. For what it's worth, the part that tripped me up was the actual closure of the stream. I was attempting to use it with `async`/`await` as well, and ideally didn't want to write boilerplate code.

Here's what I ended up with (it's in the context of an s3 get).
```ts
import tar from 'tar';
import util from 'util';
import stream from 'stream';

import s3 from './s3';

const pipeline = util.promisify(stream.pipeline);

const getFileList = async (s3Bucket: string, s3Key: string) => {
  const s3Options = {
    Bucket: s3Bucket,
    Key: s3Key
  };

  const files = [];

  const s3ReadStream = s3.getObject(s3Options).createReadStream();
  const tarWriteStream = tar.t({
    onentry: entry => files.push(entry.path)
  });
  await pipeline(s3ReadStream, tarWriteStream);

  return files;
}

export default getFileList;
```
