### ISSUE TITLE
tar.extract silently exits and writes 0 bytes

### ISSUE THREAD

**Issue by skeet70** [npm/node-tar#232]
Investigating https://github.com/mapbox/node-pre-gyp/issues/477.

[This extract call](https://github.com/mapbox/node-pre-gyp/blob/590da5603bb77df9583bfdc54d05d2267cadb364/lib/install.js#L180-L184) doesn't emit `close`/`error`/`finish` and leads to a higher level exit being called. The `onentry` call does happen, but looking at the disk after everything exits, nothing was actually extracted.

```
ls -l bin-package/
total 0
-rw-rw-r-- 1 travis travis 0 Sep 23 20:53 index.node
```

Seems like this is directly related to https://github.com/isaacs/minipass/issues/9

**Comment by isaacs** [comment]
Should be fixed now.
