### ISSUE TITLE
Two tar 4.4.13 dependencies (yallist and minizlib) no longer compatible with node 5 (5.12.0).

### ISSUE THREAD

**Issue by damellis** [npm/node-tar#233]
It looks like tar 4.x is intended to be compatible with old versions of node. I'm using node 5.12.0 and getting errors when using tar 4.4.13. It looks like two dependencies updated in ways that are no longer compatible w/ node 5:

https://github.com/isaacs/minizlib/issues/11
https://github.com/isaacs/yallist/issues/21

So to keep tar 4 compatible with node 5, it may be necessary to pin to yalllist 3.0.3 and minizlib 1.2.2 (or switch to newer versions if those issues get resolved).

**Comment by isaacs** [comment]
Fixed.

Tar v5 requires node >= 8.  There will never be another tar v4 release.

Please stop using Node 4.  It's insecure.  The node community has moved on.
