### ISSUE TITLE
npm install node-tar not working

### ISSUE THREAD

**Issue by xeroxstar** [npm/node-tar#236]
Trying to install node-tar with npm but i am getting the error:
```
npm ERR! code E404
npm ERR! 404 Not Found: node-tar@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-29T06_06_33_655Z-debug.log
```

**Comment by ssmirr** [comment]
@xeroxstar the error says `node-tar` doesn't exist, and thats because the package name on npm is `tar`. You should use `npm install tar` instead.
