### ISSUE TITLE
Provide changelog or release notes

### ISSUE THREAD

**Issue by medikoo** [npm/node-tar#237]
There seem no resources which will provide information on what actually changed between versions

e.g. to  learn what breaking changes were introduced with v5.0.0 (whether it's safe to upgrade from v4.0.0 in context of given project) one needs to read code diff. That's far from ideal.

Seems related to #113 which was closed without any solution given

**Comment by isaacs** [comment]
f9555ddc60d5199ff92f99b2ddff7629f4c2dd35

**Comment by medikoo** [comment]
Thank you @isaacs !
