### ISSUE TITLE
Extract does not fire error on corrupted tar

### ISSUE THREAD

**Issue by satazor** [npm/node-tar#24]
http://cl.ly/3j3v1o161M0m

The tar file above is a tar.gz file that failed while downloading. If passed into `Extract()` there's no `end` or `error` event being fired. It simply silently fails. I tracked down all the `end` events in streams and it gets fired correctly for every stream (gunzip, block stream, etc) except for `_fst` (filestream). Can this be related to the padding applied to block stream?

Sample code:

```js
var fs = require('fs');
var zlib = require('zlib');
var tar = require('tar');

console.log('start');

fs.createReadStream('foo.tar.gz')
.on('end', console.log.bind(console, 'fs read end'))
.on('error', console.log.bind(console, 'error'))
.pipe(zlib.createGunzip())
.on('end', console.log.bind(console, 'gunzip end'))
.on('error', console.log.bind(console, 'error'))
.pipe(tar.Extract({
    path: 'foo'
}))
.on('error', console.log.bind(console, 'error'))
.on('end', console.log.bind(console, 'done'));
```

**Comment by othiym23** [comment]
This is finally fixed, by the same fix for #58. Thanks for filing this, and I'm sorry it took us so long to get around to dealing with it!
