### ISSUE TITLE
[BUG] Memory usage is huge

### ISSUE THREAD

**Issue by Telokis** [npm/node-tar#240]
# What / Why
> Using `tar.c` to tar a directory containing huge files takes an astonishing 8GB of RAM even though I am using a stream.

## When
I try to bundle this directory and its content:
![image](https://user-images.githubusercontent.com/6382729/69802359-b2966e80-11d9-11ea-8c49-76b26495aa57.png)

(`huge.txt` is a simple `yes > huge.txt` that ran for some minutes)

## Where
* Windows 10
* Node 12.2.0
* Npm 6.11.3
* node-tar@5.0.5

## How
I did a very simple test file to compare node-tar to [tar-fs](https://github.com/mafintosh/tar-fs):

```js
const nodeTar = require("tar");
const tarFS = require("tar-fs");
const { performance, PerformanceObserver } = require("perf_hooks");
const path = require("path");
const fs = require("fs");

const streamToPromise = stream =>
    new Promise((resolve, reject) => {
        stream.on("end", resolve);
        stream.on("close", resolve);
        stream.on("finish", resolve);
        stream.on("error", reject);
    });

const formatNumber = n => {
    const parts = n.toString().split(".");

    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, " ");

    return parts.join(".");
};

const obs = new PerformanceObserver(list => {
    const entry = list.getEntries()[0];
    console.log(`${entry.name}:`, `${formatNumber(Math.floor(entry.duration / 1000))} seconds`);
});
obs.observe({ entryTypes: ["measure"] });

const testStream = async (outFile, stream) => {
    let maxRAM = 0;
    const handle = setInterval(() => {
        maxRAM = Math.max(maxRAM, process.memoryUsage().rss);
    });

    performance.mark("A");
    const outStream = fs.createWriteStream(outFile);

    stream.pipe(outStream);

    await streamToPromise(stream);
    clearInterval(handle);
    performance.mark("B");

    performance.measure("Time taken to tar files", "A", "B");
    console.log("Max RAM usage:", `${formatNumber(Math.floor(maxRAM / 1024 / 1024))} Mo`);
    performance.clearMarks();
};

const inFiles = ["big_dir"];
const outFile = path.resolve(__dirname, "file-out.tar");

(async () => {
    let stream;

    console.log("Testing node-tar:");
    stream = nodeTar.c(
        {
            gzip: false,
            follow: true,
            cwd: __dirname,
        },
        inFiles,
    );
    await testStream(outFile, stream);

    console.log();

    console.log("Testing tar-fs:");
    stream = tarFS.pack(__dirname, {
        entries: inFiles,
        dereference: true,
    });

    await testStream(outFile, stream);
})();
```

#### Two cases where I also added `"node_modules"` to the `inFiles` just to add a "lots of small files" use case.
![image](https://user-images.githubusercontent.com/6382729/69802934-048bc400-11db-11ea-8a86-35dcb6a27f4c.png)
![image](https://user-images.githubusercontent.com/6382729/69802948-0e152c00-11db-11ea-8e71-760a4c361a2c.png)

#### Only `big_dir` as input. Don't know why `tar-fs` used more RAM even though I removed an input.
![image](https://user-images.githubusercontent.com/6382729/69802959-15d4d080-11db-11ea-98e8-39316270ac05.png)
![image](https://user-images.githubusercontent.com/6382729/69803336-381b1e00-11dc-11ea-83af-72133d6d6f6a.png)

### Expected Behavior
Since I'm using `stream`s I expect the library to never use much RAM. It is very much limited in my use case and I'd rather wait longer if it meant having predictible and low RAM usage.

**Comment by isaacs** [comment]
It looks like the issue is that the `fs.createWriteStream` is accepting writes ahead of them being flushed out of the stream's buffer to the file.  (Of course, part of why node-tar is going faster than tar-fs is that it's writing as fast as it's allowed, which is also why it's pushing more data into the FileWriteStream's buffer.)

If you have tar write directly to the file, it'll go faster _and_ use less memory if you just specify the file you want it written to, with something like this:

```js
    await nodeTar.c(
        {
            gzip: false,
            follow: true,
            cwd: __dirname,
            file: outFile
        },
        inFiles,
    );
```
