### ISSUE TITLE
How to tgz a file

### ISSUE THREAD

**Issue by karthik22061993** [npm/node-tar#243]
In my script (located in $HOME/customdir/scripts/testscript.js)  I using this npm package, I want to tgz a files and a directory located in $HOME directory.  I could tgz the files but when I unzipped it I found it had zipped directory all togather, I want to tgz only the files and its directory . 

In the document I  noDirRecurse Do not recursively archive the contents of directories. [Alias: n]

I am not sure how to use this option. Can someone help me

**Comment by karthik22061993** [comment]
Uncaught ReferenceError: noDirRecurse is not defined

This is what I tried 
function DoArchive() {
	let homedir = process.env.HOME;
	var sAnsysTempDir = homedir + path1.sep + '.somedir';
	let sZipFile = 'Diagnostics_' + GetTimestamp() + '.tgz';
	let sZipPath = homedir + path1.sep + sZipFile;
    if (!fs1.existsSync(sTempDir)) {
    	fs1.mkdirSync(sTempDir);
	}

	g_sConsoleOutput += "\n######################################################\n";
	g_sConsoleOutput += "\nCreating zip file...\n";
	UpdateConsole(g_sConsoleOutput);
	
    var sLogFile = homedir + path1.sep + 'SubscriptionDiagnostics.txt';
    var pLogFile = fs1.createWriteStream(sLogFile);
    pLogFile.write(g_sConsoleOutput);
    pLogFile.on('finish', () => {  
		tar.c(
			{
			  gzip: noDirRecurse,
			  file: sZipFile
			},
			[sTempDir,  sLogFile]
		  ).then(_ => {  
				var sHtml  = "<br>\n";  
				sHtml += "The following zip file : " + sZipPath;
				sHtml += "<br><br>has been created with diagnostics information. Please send it to ANSYS support."
				DoDone();
				$("#sContent").html(sHtml);
            })
    });
    pLogFile.end();
}

**Comment by karthik22061993** [comment]
Basically how to apply change  directory on this npm package (tar -C )

**Comment by isaacs** [comment]
You can use the equivalent of `-C` by passing a `C` option (or `cwd` if you prefer).

This is clearly wrong:

```
		tar.c(
			{
			  gzip: noDirRecurse,
			  file: sZipFile
			},
```

It should probably be something like this:

```
		tar.c(
			{
			  gzip: true,
                           noDirRecurse: true,
			  file: sZipFile
			},
```

The documentation is quite extensive.  I suggest you consult it, it contains the answers to most of the issues you're running into: https://github.com/npm/node-tar#tarcoptions-filelist-callback-alias-tarcreate

**Comment by isaacs** [comment]
Note that, just as when doing `tar -C <directory>`, the file paths added to the created archive will all be relative to the new cwd.

So, if you have a file at `dir/subdir/file.txt`, then you'd do:

```js
tar.c({
  file: 'archive.tgz',
  gzip: true,
  cwd: './dir',
}, [ 'subdir/file.txt' ]) // not dir/subdir/file.txt
```
