### ISSUE TITLE
Is it possible to process files from a large tar file one by one?

### ISSUE THREAD

**Issue by josdejong** [npm/node-tar#245]
# What / Why

I have a large tar file of about 100GB containing about 1 million files. I want to read the files and send them to a server. Currently I do:

```js
tar.t({
  file: TAR_FILE,
  onentry: async (entry) => {
    if (entry.type === 'File') {
      await fetch(URL, {
        method: 'POST',
        headers: { Authorization: `Bearer ${TOKEN}` },
        body: entry
      })
    }
  }
})
```
This works like a charm, except that it fires hundreds or even thousands of requests at the same time to the server. I would like to read and send the files one by one to the server. I've played around with the options `sync` and `noResume`, but can't find a working solution. The docs say:

> `noResume` By default, `entry` streams are resumed immediately after the call to `onentry`. Set `noResume: true` to suppress this behavior. Note that by opting into this, the stream will never complete until the entry data is consumed.

That sounds like the application would have to read the whole 100GB file in memory before being able to process the files one by one.

Is there a way to process files in a large tar file one by one?

## Where
* n/a

## Who
* n/a

## References
* n/a

**Comment by isaacs** [comment]
The best approach here is to use `noResume`, and process the data yourself.  It won't have to read everything into memory, it'll just throw it away.

```js
tar.t({
  file: TAR_FILE,
  noResume: true,
  onentry: async entry => {
    // passing the entry as the fetch body will cause its data to be consumed
    await fetch(URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${TOKEN}` },
      body: entry,
    })
  }
})
```

I haven't checked, but I think this will still send out as many entries as it has already read.  If so, and you want to stack up the requests so you're only doing one at a time, you could use a trick like this:

```js
let fetchPromise = Promise.resolve()
tar.t({
  file: TAR_FILE,
  noResume: true,
  onentry: async entry => {
    await fetchPromise
    // passing the entry as the fetch body will cause its data to be consumed
    fetchPromise = fetch(URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${TOKEN}` },
      body: entry,
    })
    await fetchPromise
  }
})
```

**Comment by josdejong** [comment]
Thanks isaacs, this helps a lot!

At first I couldn't get `noResume` working, it didn't do anything, but I finally figured out why. I did this:

```js
tar.t({
  file: TAR_FILE,
  noResume: true,
  onentry: async (entry) => {
    if (entry.type === 'File') {
      await fetch(URL, {
        method: 'POST',
        headers: { Authorization: `Bearer ${TOKEN}` },
        body: entry
      })
    }
  }
})
```
There is a ` if (entry.type === 'File') {...}` which reads the entry body of files, but non-file entries (directories) are ignored, do not consume the entry body, so nothing happens :joy: . I changed it to the following:

```js
tar.t({
  file: TAR_FILE,
  noResume: true,
  onentry: async (entry) => {
    if (entry.type === 'File') {
      await fetch(URL, {
        method: 'POST',
        headers: { Authorization: `Bearer ${TOKEN}` },
        body: entry
      })
    } else {
      // directory. Read entry contents so we can continue
      await entry.read()
    }
  }
})
```
And now it works like a charm. 

This is indeed still processing entries in parallel. Your idea of using a promise to block the other entries from reading in parallel works too so I'm totally happy with a fully working solution :+1: .

**Comment by RealAlphabet** [comment]
> Thanks isaacs, this helps a lot!
> 
> At first I couldn't get `noResume` working, it didn't do anything, but I finally figured out why. I did this:
> 
> ```js
> tar.t({
>   file: TAR_FILE,
>   noResume: true,
>   onentry: async (entry) => {
>     if (entry.type === 'File') {
>       await fetch(URL, {
>         method: 'POST',
>         headers: { Authorization: `Bearer ${TOKEN}` },
>         body: entry
>       })
>     }
>   }
> })
> ```
> 
> There is a ` if (entry.type === 'File') {...}` which reads the entry body of files, but non-file entries (directories) are ignored, do not consume the entry body, so nothing happens 😂 . I changed it to the following:
> 
> ```js
> tar.t({
>   file: TAR_FILE,
>   noResume: true,
>   onentry: async (entry) => {
>     if (entry.type === 'File') {
>       await fetch(URL, {
>         method: 'POST',
>         headers: { Authorization: `Bearer ${TOKEN}` },
>         body: entry
>       })
>     } else {
>       // directory. Read entry contents so we can continue
>       await entry.read()
>     }
>   }
> })
> ```
> 
> And now it works like a charm.
> 
> This is indeed still processing entries in parallel. Your idea of using a promise to block the other entries from reading in parallel works too so I'm totally happy with a fully working solution 👍 .

Sorry to bring this closed issue back, but I would like to add a little information. If you want to skip entries, **DO NOT use `entry.read()`** but `entry.resume()` instead.

## Why?
Firstly `entry.read()` doesn't return a promise and returns the buffered data. This means that if you have a large file, because of the backpressure you won't consume all the input by calling `entry.read()` once and the `onentry` function won't be called again for subsequent files. `entry.resume()` will replicate the default operation that you disabled by adding the `noResume: true` option, which will allow the library to continue listing files.

**Comment by isaacs** [comment]
Thanks for the update. Yes, that is correct, entry.resume() is the thing to use here.
