### ISSUE TITLE
Drop mkdirp package

### ISSUE THREAD

**Issue by Umoxfo** [npm/node-tar#248]
Related with #247

**Comment by spawn-guy** [comment]
nice one! it also covers this recent issue 
https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
as i see this is the only dependency that requires `minimist`

**Comment by ruyadorno** [comment]
As discussed in #247, **mkdirp** is a package that is actively supported by @isaacs, handles a bit more edge cases than the standard nodejs implementation and with these in mind, we do not intend to drop it in the foreseeable future.

Thanks for the heads up with the advisories 😄 it should all have been fixed a while ago.
