### ISSUE TITLE
[BUG] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by VietNguyenQuoc** [npm/node-tar#251]
# What / Why

> My code is trying to make a tarball from 2 files by streaming.

### Current Behavior

* It has error "The "path" argument must be of type string. Received type object".

Here's my code, errors coming from line 

```
> sourceStreamA.pipe(pack, { end: false})
```

```js
const tar = require("tar");
const fstream = require("fstream");
const path = require("path");

const dest = path.resolve(process.argv[2]);
const sourceA = path.resolve(process.argv[3]);
const sourceB = path.resolve(process.argv[4]);

const pack = new tar.Pack();
pack.pipe(fstream.Writer(dest));

let endCount = 0;
const onEnd = () => {
  if (++endCount === 2) {
    pack.end();
  }
};

const sourceStreamA = fstream.Reader(sourceA).on("end", onEnd);
const sourceStreamB = fstream.Reader(sourceB).on("end", onEnd);

sourceStreamA.pipe(pack, { end: false });
sourceStreamB.pipe(pack, { end: false });
```

**Comment by isaacs** [comment]
It looks like you're using a very outdated version of tar (or incorrectly using fstream with a new version of tar).

Please see the current documentation for usage of the currently supported tar version.

**Comment by ayushpratap2494** [comment]
is this issue resolved ?

**Comment by ayushpratap2494** [comment]
I believe this is taken from node.js design patterns book ?
is this issue resolved ?
