### ISSUE TITLE
Stop using process.umask()

### ISSUE THREAD

**Issue by isaacs** [npm/node-tar#252]
> Refs: https://github.com/nodejs/node/issues/32321
> 
> Summary: `process.umask()` (no args) will be deprecated and removed.
> 
> I couldn't quite divine what `lib/config/defaults.js` uses `process.umask()` for but in most cases you don't need to deal with the umask directly - the operating system will apply it automatically.
> 
> Example:
> ```js
> const mode = 0o777 & ~process.umask();
> fs.mkdirSync(dir, mode);
> ```
> Computing the file mode that way is superfluous, it can be replaced with just this:
> ```js
> fs.mkdirSync(dir, 0o777);
> ```

https://github.com/nodejs/node/issues/32321#issuecomment-608549694

cc @bnoordhuis

**Comment by isaacs** [comment]
- Add a `chmod: false` option to unpack.  In this mode, just create the file with the entry mode, and let it ride with whatever the OS gives us.
- If `chmod:false` is not set, then create the file with the entry.mode, stat the file, and chmod if different.  This will be slower than the current approach, unfortunately.

**Comment by isaacs** [comment]
Note: even though it's potentially slower, creating the file and then checking the mode is a more technically correct approach, as it is resilient against `process.umask()` changing during the unpack, or returning an incorrect value.

**Comment by bnoordhuis** [comment]
FWIW, I did some quick, completely unscientific benchmarks on Linux and changing create-close to create-fchmod-close slows it down by just under 15%:
```js
// As root, run `echo 3 > /proc/sys/vm/drop_caches` first
'use strict';
const { O_CREAT, O_WRONLY } = require('fs').constants;
const { openSync, closeSync, unlinkSync } = require('fs');
let { fchmodSync } = require('fs');
if (process.argv[2]) fchmodSync = () => {};

const N = 1e4;
const files = [];
for (let i = 0; i < N; i++) files.push('/tmp/xyzzy' + i);

const start = Date.now();
for (const file of files) {
  const fd = openSync(file, O_CREAT|O_WRONLY);
  fchmodSync(fd, 0o666);
  closeSync(fd);
}
const end = Date.now();

console.log(start, end, end - start);
for (const file of files) unlinkSync(file);
```
15% sounds like a lot, however:

1. The benchmark doesn't write any data. Writing 4x4k blocks shrinks the relative gap to <5%.

2. There is only a statistically significant difference when the cache is already warmed up.

I assume cold caches are the common case for node-tar because you don't normally unpack the same tarball to the same location 10 times in a row. (Well, I don't, anyway.)

**Comment by ql-nano** [comment]
If you really need to use 
```javascript
process.umask()
```
(without args), then you may use [**get-umask**](https://www.npmjs.com/package/get-umask)  module. It suppresses those annoying warnings. And yeah, it's written by me.

**Comment by isaacs** [comment]
Suppress warnings by using `{ noChmod: true }`, so that it won't have to calculate anything.  Otherwise, there's no way around having to get the process umask, or else it's a big security problem.
