### ISSUE TITLE
[QUESTION] Is tar 6 supported on Node 12?

### ISSUE THREAD

**Issue by aminya** [npm/node-tar#260]
# What / Why
Is tar 6 supported on Node 12? The [CI shows failure](https://travis-ci.org/github/npm/node-tar/builds/718069381), but [package.json](https://github.com/npm/node-tar/blob/7028aeb3f5bb843bf80af8f5af09c47c3d97503f/package.json#L38) shows Node >= 10.

**Comment by isaacs** [comment]
https://github.com/npm/node-tar/runs/3235437182?check_suite_focus=true

**Comment by isaacs** [comment]
yes
