### ISSUE TITLE
Show progress

### ISSUE THREAD

**Issue by zLupa** [npm/node-tar#262]
# What / Why
Give a callback when compress to report the progress of the file compressing or extracting.
Like a percentage or the bytes that has been written
Some
## Where
npm public registry

### Current Behavior
To do that currently is so verbose, is good to have a own tool from the official repository.

### Expected Behavior
Whenever the callback is called, return a progress event, in that progress event show percentage or the bytes written so far.

## References
Like that option has in https://www.npmjs.com/package/@google-cloud/storage
![google storage](https://user-images.githubusercontent.com/56929033/93377477-6af8d600-f831-11ea-9874-2be3a47756be.png)

**Comment by isaacs** [comment]
Sorry, that is not a priority for this module, which is purely concerned with handling bytes, not visuals.

I recommend using an `onentry` event to get at the entry objects as they are created, or some other stream-progress type module out there.
