### ISSUE TITLE
Options of the tar.Parse() constructor function

### ISSUE THREAD

**Issue by caillou** [npm/node-tar#263]
# What / Why

When trying to fix the `@types/tar` declaration files for `tar.Parse()`, I noticed to following:

Both the [Readme](https://github.com/npm/node-tar#class-tarparse) and the [tests](https://github.com/npm/node-tar/blob/eea7dd7cf5d1e1d0a1a5a983b69ac8dd774bb4ce/test/parse.js#L90) suggest that the `tar.Parse()` constructor function expects options.

As I see it, the [implementation](https://github.com/npm/node-tar/blob/7028aeb3f5bb843bf80af8f5af09c47c3d97503f/benchmarks/node_modules/tar/lib/parse.js#L27) does not accept these options: 

```javascript
function Parse () {
  var me = this
  if (!(me instanceof Parse)) return new Parse()
  // ...
}
```

Am I missing something?

**Comment by isaacs** [comment]
That is the `Parse` class from tar prior to version 3, included in the benchmark script only to compare to the previous implementation.  The [current implementation](https://github.com/npm/node-tar/blob/main/lib/parse.js#L66) does accept an options object.
