### ISSUE TITLE
[BUG] tar does not resolve when extracting a tarball including multiple symlinks that point at the same file

### ISSUE THREAD

**Issue by ewanharris** [npm/node-tar#265]
# What / Why

When extracting a tarball that includes multiple symlinks that point at the same file, tar will never resolve (or call the callback).

This only occurs when running on Windows and symlinks cannot be created (i.e. not running as an administrator or with developer mode enabled). However, the EPERM failures are not fatal errors so I would consider what's occurring here a bug. This works fine on tar@4.4.13 and looks to have appeared around 5.X

In larger tarballs when this situation occurs this causes the extraction to finish and the extracted folder to be incomplete and invalid.

## When

* tar: 5.0.5, 6.0.5
* Node.js: 10.23.0, 12.20.0

* n/a

### Current Behaviour

In step 3 `done!` is never logged

### Steps to Reproduce
1. Download [output-with.tar.gz](https://github.com/npm/node-tar/files/5604292/output-with.tar.gz) and 
[output.tar.gz](https://github.com/npm/node-tar/files/5604293/output.tar.gz)
2. Run the below code in a node repl from the same folder as the tar.gz file (this is the tarball that works fine)
```js
require('tar').x({file: 'output.tar.gz'})
    .then(() => console.log('done!'))
    .catch((err) => console.log(err));
```
3. Run the below code in a node repl from the same folder as the tar.gz file
```js
require('tar').x({file: 'output-with.tar.gz'})
    .then(() => console.log('done!'))
    .catch((err) => console.log(err));
```

### Expected Behavior

At step 3, `done!` is logged and extraction is completed

**Comment by ewanharris** [comment]
Curiously, when passing `sync: true` this doesn't occur

**Comment by isaacs** [comment]
Can you test this again?  I can't seem to reproduce on the latest v6.

**Comment by ewanharris** [comment]
I can still repro this issue on tar 6.1.3/Node.js 14.17.4

Do you have symlink creation disabled? `mklink foo package.json` should fail with `You do not have sufficient privilege to perform this operation.`. If you have Developer Mode enabled then disabling it _should_ disable symlink creation
