### ISSUE TITLE
[QUESTION] Is node-tar support pigz ?

### ISSUE THREAD

**Issue by sinoon** [npm/node-tar#267]
# What / Why

[Pigz](https://zlib.net/pigz/) is a faster way to unpack tar with gzip format. If we can use in node-tar, will save time

## References

[Pigz](https://zlib.net/pigz/)

**Comment by isaacs** [comment]
Node-tar uses the zlib binding in Node.js.  If you would like node to switch from zlib to pigz, that's a conversation to have at htts://github.com/nodejs/node
