### ISSUE TITLE
[BUG] <title>'cwd' not working 

### ISSUE THREAD

**Issue by garfieldull** [npm/node-tar#269]
# What / Why
` const tarFile = tempfile('.tgz');`
`const writeStream = fs.createWriteStream(tarFile);`
` tar.c({ gzip: true, wd: path.resolve(dir) }, [dir]).pipe(writeStream);`
we need a tarball with relative path, I set the 'cwd' option according to the document, but the generated tarball still has the whole folder structure. where is the problem? 

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by bvc** [comment]
Looks like you are assigning the entire directory in the `fileList` argument. The files and/or directories in the `fileList` should be relative to the path set for the `cwd` option.

Suppose you are at the top of a directory with the tree structure `/sample_folder/inner_folder/file.txt` the code should look like this...

```
const path = require('path')
const fs = require('fs')
const tar = require('tar')

const { join, resolve } = path

const sourceDir = resolve(join(__dirname, 'sample_folder', 'inner_folder'))
const targetFile = resolve(join(__dirname, 'example.tgz'))
const writeStream = fs.createWriteStream(targetFile)

tar.c({
  gzip: true,
  cwd: sourceDir,
}, ['file.txt']).pipe(writeStream)
```
