### ISSUE TITLE
Create a tar from objects Buffers in memory

### ISSUE THREAD

**Issue by jpillora** [npm/node-tar#27]
Is it possible to create a tar file from buffers in memory? I'm guessing I'll have to mock an fstream stream?

**Comment by isaacs** [comment]
Yes, you can do this on v3 now, but you do have to use some of the lowlevel API.  You can see some of the tests doing this using this little utility.

https://github.com/npm/node-tar/blob/master/test/make-tar.js
https://github.com/npm/node-tar/blob/master/test/parse.js#L370-L422
