### ISSUE TITLE
how can i get the file by tar.extract

### ISSUE THREAD

**Issue by flyingFlowers** [npm/node-tar#273]
```js
readStream
 .pipe(zlib.createGunzip())
.pipe(tar.extract({
   cwd: destDir
}));
```

if the destDir has lots of files, how can get the right file ?

**Comment by isaacs** [comment]
I'm not sure what "the right file" is?

(You don't need to pipe through a `zlib.createGunzip()`, tar will unzip it for you.)

**Comment by isaacs** [comment]
You can either tell it specifically which files to unpack:

```js
readStream.pipe(tar.x({ cwd: destDir }, ['files', 'to', 'unpack', ...]))
```

Or you can use an `onentry` method to see what was unpacked:

```js
const filesUnpacked = []
readStream.pipe(tar.x({
  cwd: destDir,
  onentry: entry => filesUnpacked.push(entry.absolute),
}))
```
