### ISSUE TITLE
Archive all files from folder, but without the folder itself

### ISSUE THREAD

**Issue by bayerlse** [npm/node-tar#274]
Hey there!

How can I create a tar with all files and folders from a given folder path, without the folder itself?

**For example:**

Given the following folder structure:

- test
  - folder1
    -  main.js
  - index.js

Should result in a `tar` with:

- folder1
  -  main.js 
- index.js

But when I run:

```
 await tar({ gzip: true, "test-tar.tar.gz"}, ['test'] );
```

It results in archieving also the test folder, when unpacked:

- test
  - folder1
    -  main.js
  - index.js
  
Thanks in advance!

**Comment by isaacs** [comment]
Just set the dir as the cwd, and then pass in a file inclusion list that includes all the entries in the dir.

```js
await tar.c({
  gzip: true,
  file: 'test-tar.tar.gz',
  cwd: 'test',
}, fs.readdirSync('test'))
```

**Comment by isaacs** [comment]
Example: https://gist.github.com/isaacs/0a05e95b930cc3962fa727e3c02d7161
