### ISSUE TITLE
[BUG] extractFile in lib/extract.js does not respect cwd option

### ISSUE THREAD

**Issue by danganiev** [npm/node-tar#275]
# What / Why
Call to `fs.stat(file, (er, stat) => {...})` in  `extractFile` function of `lib/extract.js` file does not respect `cwd` option. So if I call `tar.x({file:'myfile.tar.gz', cwd:'/goodfolder'})` but my app is running in `/badfolder`, `fs.stat` call will be made with `process.cwd()`, and thus if there is no `/badfolder/myfile.tar.gz`, an `Error: ENOENT: no such file or directory, stat 'myfile.tar.gz'` will be raised, even if there is `/goodfolder/myfile.tar.gz` (which I wanted)

## When
* n/a

## Where
* n/a

### Current Behavior
* n/a

### Steps to Reproduce
* n/a

### Expected Behavior
* n/a

## Who
* n/a

## References
* n/a

**Comment by isaacs** [comment]
The `cwd` option is not applied to the `file` option.  This matches the behavior of `tar(1)`'s `f` and `-C` options.

```
$ tar cvf foo.tar -C foo a b c d
a a
a b
a c
a d

$

$ ls -laF foo*
-rw-r--r--  1 isaacs  staff  3072 Aug 10 09:26 foo.tar

foo:
total 0
drwxr-xr-x   9 isaacs  staff   288 Apr  3  2020 ./
drwxr-xr-x  63 isaacs  staff  2016 Aug  9 16:14 ../
-rw-r--r--   1 isaacs  staff     0 Aug 21  2019 a
-rw-r--r--   1 isaacs  staff     0 Aug 21  2019 b
-rw-r--r--   1 isaacs  staff     0 Aug 21  2019 c
-rw-r--r--   1 isaacs  staff     0 Aug 21  2019 d
```
