### ISSUE TITLE
Compression without directory structure

### ISSUE THREAD

**Issue by yyy19961027** [npm/node-tar#278]
How to configure so that the compressed package does not have a directory structure, the desired result is ...
![1624504450(1)](https://user-images.githubusercontent.com/66300848/123197037-81793f80-d4dd-11eb-8e1c-ae2dc9e7695c.png)
![1624504600(1)](https://user-images.githubusercontent.com/66300848/123197143-af5e8400-d4dd-11eb-83ec-3dcf2ca67456.png)
I want to start with the study folder, which is the folder to be compressed, now I start from the root directory

**Comment by isaacs** [comment]
Is this the same as https://github.com/npm/node-tar/issues/274?
