### ISSUE TITLE
[QUESTION] Is it possible to get an bugfix release with latest ReDos fix for v4 too?

### ISSUE THREAD

**Issue by sseide** [npm/node-tar#285]
# What / Why
a week ago a security fix was commited to the latest "tar" release (commit 06cbde5935aa7643f578f874de84a7da2a74fe3a
"Avoid an unlikely but theoretically possible redos").

As a lot of programs out there use the older v4 line of "tar" a security bugfix release similar to the latest 4.4.15
would be extremly helpful to fix all these programs out there. Is it possible get an release of a new 4.4.16 with this fix applied?
The fix itself it seems can be applied directly to the old v4.

## Where
* npm

## Who
* n/a

## References
* commit 06cbde5935aa7643f578f874de84a7da2a74fe3a

Thanks in advance,
S. Seide

**Comment by isaacs** [comment]
Included in 4.4.16 adf3511
