### ISSUE TITLE
[QUESTION] How to add whole directory without adding "."?

### ISSUE THREAD

**Issue by zdm** [npm/node-tar#288]
Hi.
I need to add all files recursively in the some directory, files paths must be relative.

### Variant 1
```
tar.create({
cwd: pathToFolder,
}, ["."]);
```
Adds all files in the `pathToFolder` but also adds `"."`. Content of the created archive looks like this:
```
.
file1
file2
...
```
How to get rid of the `"."` entry?

### Variant 2
```
tar.create({
cwd: pathToFolder,
}, [pathToFolder]);
```
Adds all files in `pathToFolder`, `"."` entry is not added, but all path are absolute.

**Comment by isaacs** [comment]
Read the contents and add them, without adding the folder :)

```js
const fs = require('fs')
async addFilesWithoutAddingDot = async folder => {
  return tar.create({
    cwd: folder,
  }, await fs.promises.readdir(folder))
}
```

**Comment by zdm** [comment]
Yes, I already did this, thanks.
But expected for the embedded method for this popular operation.
