### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by fresheneesz** [npm/node-tar#29]
There is not even nearly enough documentation for this. 
- How are Pack's options used? At least provide a link to something that makes sense about "Global Extended Headers"
- How would I pack multiple files together?
- How does Pack actually work? Do you have to use fstream?
- Why pass in a Writer to Pack? I would have expected the usage to be input.pipe(tar).pipe(output), no?

Some examples would help too.

**Comment by isaacs** [comment]
All things are documented on v3 now, but more doc improvements are always welcome.
