### ISSUE TITLE
tar.Pack reseting the UID, GUID and date of the root folder

### ISSUE THREAD

**Issue by cranic** [npm/node-tar#30]
Hey guys, take a look at this [output/code](https://gist.github.com/cranic/2c718ddfa20ab1724c70), can someone explain to me why tar.Pack is messing the attributes of the root folder `compress/`?

**Comment by isaacs** [comment]
Is this still an issue in v3?

**Comment by isaacs** [comment]
If so, you can add `{ preserveOwner: false }` to the unpack options.
