### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by akmdyusrienpgj** [npm/node-tar#301]
# What / Why

> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

>

**Comment by NizamShah7** [comment]
# ensure that some of the current sync committee members are the slashed
    slashed_pubkeys = [state.validators[index].pubkey for index in slashed_indices]
    assert any(set(slashed_pubkeys).intersection(list(state.current_sync_committee.pubkeys)))
