### ISSUE TITLE
[Question] How to import this module to single js file so that it easy to use.

### ISSUE THREAD

**Issue by qcscofield** [npm/node-tar#305]
I want to use it in single JS file. Please tell me how to do. Thanks in advance.

**Comment by azooz-12** [comment]
> I want to use it in single JS file. Please tell me how to do. Thanks in advance.

**Comment by darcyclarke** [comment]
`npm install tar` into a project directory (which should generate a `package.json` if you don't already have one & a `node_modules` folder) & then in a node file (ex. `index.js`) write... 

```js
const tar = require('tar')
// you can now use `tar`
```

If you want to bundle this module you'll have to use third-party tools.
