### ISSUE TITLE
not compatible with gnutar@1.27.1

### ISSUE THREAD

**Issue by dominictarr** [npm/node-tar#31]
when I try to parse and repack a tarball, the result looks like a tar file,
but is not compatible with gnutar.

``` js
//extract.js
var tar = require('./')
var zlib = require('zlib')

process.stdin
  .pipe(zlib.createGunzip())
  .pipe(tar.Parse())
  .pipe(tar.Pack())
  .pipe(zlib.createGzip())
  .pipe(process.stdout)
```

then I run this command:

```
node extract.js < ~/.npm/tar/0.1.19/package.tgz | tar -tz
```

which should transform a tarball into a node-tar tarball,
and then list it's entries with the tar command.
output:

``` js
package.json
.npmignore
tar: Skipping to next header
README.md
tar: Skipping to next header
LICENCE
tar: Skipping to next header
tar.js
tar: Skipping to next header
.travis.yml
extracter.js
tar: Skipping to next header
reader.js
tar: Skipping to next header
buffer-entry.js
tar: Skipping to next header
entry-writer.js
tar: Skipping to next header
entry.js
extended-header-writer.js
extended-header.js
extract.js
global-header-writer.js
header.js
pack.js
parse.js
00-setup-fixtures.js
extract.js
header.js
pack-no-proprietary.js
pack.js
parse.js
zz-cleanup.js
fixtures.tgz
tar: Exiting with failure status due to previous errors
```

It looks like there is something messed up with the paths?
when I do: `|gunzip | less` I see that the directories have been chopped off.

``` js
package.json^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@000644 ^@001750 ^@000012 ^@0000000744 ^@12173645457^@011435 ^@0^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ustar^@00^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@000000 ^@000000 ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@{
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me/)",
  "name": "tar",
  "description": "tar for node",
  "version": "0.1.18",
  "repository": {
    "type": "git",
    "url": "git://github.com/isaacs/node-tar.git"
  },
  "main": "tar.js",
  "scripts": {
...
```

there also seems to be spaces at the end of the numbers, but there isn't spaces at the end of numbers in the tarball which does work.
Is there an option that makes this work by default? I've been looking through the npm code to see how it packs/unpacks stuff, but I can't find anything unusual.

**Comment by MeySolution** [comment]
Any ideas on this?
Happening to on ubuntu 14.04

**Comment by brycefisher** [comment]
The [pac module](http://npmjs.org/package/pac) also uses this implementation, and therefore tars created using pac can't be extracted using the Ubuntu 14.04 default tar utility (gnu-tar).

As a temporary workaround for trying to extract on Ubuntu 14.04, I've installed bsdtar (`apt-get install -y bsdtar`), but I'd love to address this compatibility issue here in the tar module.

I'm not certain if this is a different issue or the same issue, but I here's a detailed run down of [my use-case and problem](https://github.com/mikefrey/node-pac/issues/16#issuecomment-113200385)

**Comment by isaacs** [comment]
The tarballs created by this module are now working fine with gnutar and vice versa.  But there isn't a way in v3 to do stuff like `stream.pipe(Parse()).pipe(Pack()).pipe(Parse()).pipe(Pack())` which never worked anyway.  Pack reads from the file system, Unpack writes to it, Parse emits entry objects from a tar stream.  There's no parse->pack chain.  I want to add that eventually, so that we can have support for `tar cf output.tar @input.tar` stuff.
