### ISSUE TITLE
[BUG] Not installing new version

### ISSUE THREAD

**Issue by BinukaDs** [npm/node-tar#310]
# What / Why

my current tar version is 2.2.2, but I tried to upgrade it by using **npm install tar** command. but its version hasn't been updated 

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by lukekarrys** [comment]
Try running `npm install tar@latest`
