### ISSUE TITLE
update tar up to version 6 but uses old version 2.2

### ISSUE THREAD

**Issue by bamouzad1988** [npm/node-tar#318]
# What / Why

I installed the latest version of tar(npm I tar). when I am trying to install react.js in global(npm I -g create-react-app --save) it shows an error(npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.)
> n/a

## Where
npm windows 10
* n/a

## Who

* n/a

## References

* n/a

**Comment by wraithgar** [comment]
This is not a but with node-tar.  npm will only show that warning if something inside your tree is using an older version of tar.  In this case it appears to be `tar-pack` inside `create-react-app`

```sh
$ npm ls tar
cra@ /Users/wraithgar/Development/npm/scratch/cra
└─┬ create-react-app@5.0.1
  └─┬ tar-pack@3.4.1
    └── tar@2.2.2
```
