### ISSUE TITLE
[BUG] Support for zip files? (Error: TAR_BAD_ARCHIVE: Unrecognized archive format)

### ISSUE THREAD

**Issue by NicolasCwy** [npm/node-tar#319]
# What / Why

Trying to extract a .zip file

## When

Trying to follow `tar xzf file.zip`
```
tar.x({
  f: filePath
})
```

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

Throws an error `Error: TAR_BAD_ARCHIVE: Unrecognized archive format`

### Expected Behavior

Extracts zip file

## Who

* n/a

## References

* n/a

**Comment by avivazulay1** [comment]
trying:  createReadStream('/test/test.tar.gz')
        .pipe(tar.x({ strip: 1, C: '/test2/' }))
        .on('error', (err) => {
            console.log('Error during untar for ' + err)
        })
        
        
Getting: "Error during untar for Error: TAR_BAD_ARCHIVE: Unrecognized archive format"

Will be glad for help

**Comment by wraithgar** [comment]
this only works on raw tar data. if it has been compressed in any way (i.e. by zip or gz bz2) it needs to be uncompressed first.
