### ISSUE TITLE
[BUG] Typing issue with minipass

### ISSUE THREAD

**Issue by Stono** [npm/node-tar#320]
# What / Why
Cross linking an issue I raised on minipass https://github.com/isaacs/minipass/issues/40#issue-1276495125 as it isn't clear to me the best place to raise it.

When installing the latest version of `tar` in typescript, you get the following during the build:

```
https://github.com/isaacs/minipass/pull/24 9.278 node_modules/@types/tar/index.d.ts(252,36): error TS2709: Cannot use namespace 'MiniPass' as a type.
```

Pinning minipass as a peer dependency in my project "fixes" it:

```
  "peerDependencies": {
    "minipass": "3.2.1"
  }
```

**Comment by wraithgar** [comment]
I don't think pinning to an older version of minipass is a good solution here.

This seems to be an issue w/ the `@types` modules associated with `tar` / `minipass` and not the modules themselves.  Those are sourced from the `DefinitelyTyped` repo and not maintained by npm.  That repo is probably the best place to raise issues like this.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tar
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/minipass

It appears that [minipass](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b1531302ae0883690b6424400d7b9e9295c6277f/.github/CODEOWNERS#L4674) does have a codeowner, but tar does not.

**Comment by nex3** [comment]
I believe the root issue here is https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60901.

**Comment by theaussiepom** [comment]
The issue is that from version 3.2.0 minipass publishes it's own types. DefinatelyTyped contains minipass types up until 3.1.2. Types were therefore not considered when consuming "tar" and when minipass was versioned at 3.1.2. This is why the proposed workaround by

**Comment by theaussiepom** [comment]
Sorry @nex3. I just realised that I pretty much duplicated what you said in your link

**Comment by theaussiepom** [comment]
It appears that is not a good solution :(
https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-import-default-of-export-equals.md
