### ISSUE TITLE
node-tar pack should allow the uid+gid to be overwritten

### ISSUE THREAD

**Issue by dnwe** [npm/node-tar#39]
A common use case when creating a tar is to override the source filesystem uid+gid with 0:0 when creating the tar entries, so that when the tar is extracted by a root user it will correctly be written with root:root as the owner/group, rather than inheriting the uid+gid stored with the .tgz

e.g.,

```
$ tar -zcv --owner=root --group=root --numeric-owner -f /tmp/filename.tgz package/
$ cd /tmp && sudo tar -zxf /tmp/filename.tgz
$ ls -l package/*
-rw-r--r-- 1 root root package/package.json
etc.
```

Currently if I create a tar using node-tar and distribute it to someone who untars it as root, the files will be written with whatever uid/gid my user happens to have on the machine on which I created the tar

**Comment by tamird** [comment]
Also affects JSPM https://github.com/jspm/jspm-cli/issues/1902.

**Comment by tamird** [comment]
Looks like this needs an upstream change as well, since the chmod is done in https://github.com/npm/fstream/blob/master/lib/writer.js#L194:L212.

**Comment by isaacs** [comment]
In v3, this will be possible by setting `{ preserveOwner: false }` when extracting.  (Or, to omit the uid/gid entirely, you can pack with `{ portable: true }`.)

**Comment by isaacs** [comment]
v3 is shipped.
