### ISSUE TITLE
[Q] The way not to use posix headers ?

### ISSUE THREAD

**Issue by sparkleholic** [npm/node-tar#40]
Hi @isaacs 
Is there any way to make `tar` to force not to use `posix headers`

I encountered an issue that some certain tar extractor module does not support `posix headers` properly..
So, I wonder if there is any way not to use `posix headers` in using this `tar` node module like this.
`https://dev.openwrt.org/browser/trunk/tools/ipkg-utils/patches/200-force_gnu_format.patch?rev=34261`

**Comment by isaacs** [comment]
I didn't add this for the v3 rewrite because it seems like it'd only ever result in an incorrect entry.  Pax headers are not added unless something in the header cannot be properly encoded in a tar header block.

What extractor are you using?
