### ISSUE TITLE
Extracting executable from tar causes file permission loss

### ISSUE THREAD

**Issue by prachikhadke** [npm/node-tar#53]
Untarring an executable file from a tar using the library strips the file of its executable permission.

**Comment by terotil** [comment]
Are permission flags on roadmap?

**Comment by terotil** [comment]
Weird thing. Absolutely positively had this problem yesterday, but now I can't reproduce.

**Comment by prachikhadke** [comment]
Not sure what you mean by roadmap. But I reproduced this issue several times. I ended up just running my script using 'sh <scriptname>' in my code.

**Comment by isaacs** [comment]
Works in v3.
