### ISSUE TITLE
Reliance on local system when packing?

### ISSUE THREAD

**Issue by GretaCB** [npm/node-tar#57]
Curious if and how the local OS affects the use of this module. Does `node-tar` essentially mock the system tar lib or does it utilize the system's local tar lib somehow? 

The reason I'm asking is because I'm using this module for Packing tars, then later validating the file by inspecting for the `ustar` magic number. This check fails if a tar contains an extended tar header and has `PaxHeader` in the filepath, and I'm not sure how that header is being created. The only thing I can think of is that the local system is causing this. I noticed you test for it [here](https://github.com/npm/node-tar/blob/master/test/pack.js#L33).

Any input is much appreciated, thank you!

**Comment by GretaCB** [comment]
I think I should rephrase my question. Noticed there are [specific situations](https://github.com/npm/node-tar/blob/f4151128c585da236c6b1e278b762ecaedc20c15/lib/header.js#L35-L37) you might create an extended header.

>// parse a 512-byte header block to a data object, or vice-versa
// If the data won't fit nicely in a simple header, then generate
// the appropriate extended header file, and return that.

What are some examples of situations where you would create an extended header?

**Comment by isaacs** [comment]
This module does not utilize anything about the system's tar implementation.  It exists primarily to free [npm](https://github.com/npm/npm) from the vagaries of operating systems' tar(1) programs.  (Don't get me started, seriously.  Tar is not a spec, it is an oral tradition at best.)

What tar program are you using to verify the results?  node-tar will create an extended header whenever it has a long filename, a long link target, or any other data that won't fit in the standard 512 byte tar header.  Modern tar implementations (ie, those created in the last 20 years or so) *should* skip over those `PaxHeader` entries, but if you're writing your own program for this, then you'll have to inspect the "type" entry at the 156th byte of the header.  That byte will contain an ascii character.  Here's what they mean:

```
// paths match the values of Stats.isX() functions, where appropriate
var types =
  { 0: "File"
  , "\0": "OldFile" // like 0
  , 1: "Link"
  , 2: "SymbolicLink"
  , 3: "CharacterDevice"
  , 4: "BlockDevice"
  , 5: "Directory"
  , 6: "FIFO"
  , 7: "ContiguousFile" // like 0
  // posix headers
  , g: "GlobalExtendedHeader" // k=v for the rest of the archive
  , x: "ExtendedHeader" // k=v for the next file
  // vendor-specific stuff
  , A: "SolarisACL" // skip
  , D: "GNUDumpDir" // like 5, but with data, which should be skipped
  , I: "Inode" // metadata only, skip
  , K: "NextFileHasLongLinkpath" // data = link path of next file
  , L: "NextFileHasLongPath" // data = path of next file
  , M: "ContinuationFile" // skip
  , N: "OldGnuLongPath" // like L
  , S: "SparseFile" // skip
  , V: "TapeVolumeHeader" // skip
  , X: "OldExtendedHeader" // like x
  }
```

**Comment by isaacs** [comment]
So, to answer your question, an extended header will be created whenever the field value is larger than the allotted field size in the 512 byte tar header.

Those field sizes are, in order:

```
fieldSize[path] = 100
fieldSize[mode] = 8
fieldSize[uid] = 8
fieldSize[gid] = 8
fieldSize[size] = 12
fieldSize[mtime] = 12
fieldSize[cksum] = 8
fieldSize[type] = 1
fieldSize[linkpath] = 100
//...
fieldSize[ustar] = 6
fieldSize[ustarver] = 2
fieldSize[uname] = 32
fieldSize[gname] = 32
fieldSize[devmaj] = 8
fieldSize[devmin] = 8
fieldSize[prefix] = 155
fieldSize[fill] = 12
```

So, you would see an extended header created whenever one of those fields is longer than the allotted number of bytes, or contains any non-ascii characters.

**Comment by GretaCB** [comment]
Awesome, thanks so much for the response @isaacs !
