### ISSUE TITLE
Issue in extract from huge file (>2GB) and untars it into a file instead of a folder

### ISSUE THREAD

**Issue by poddars** [npm/node-tar#62]
When untarring the file of size 2.44GB (contains 5 files). Using the extracter.js example, it untars successfully into a file of size 74kb with no error. Another issue was, instead of untarring it into folder, it extracts the contents into a file. Why would it extract the contents to a file?

**Comment by isaacs** [comment]
I don't exactly understand the question.  Is this still an issue in v3?  Can you share an example script?
