### ISSUE TITLE
Can't extract tar components into directory that doesn't have +x permission.

### ISSUE THREAD

**Issue by danfuzz** [npm/node-tar#7]
If a tarball contains a directory that isn't set to be searchable (+x permission flag), then the "tar" module will fail to extract its contents.

This is admittedly an odd corner case, but it came up in practice (see [Hogan issue #52](https://github.com/twitter/hogan.js/issues/52)). And, FWIW, the traditional "tar" clients seem to handle this case, even though the resulting output isn't particularly useful.

Here's a quick script that demos the problem.

``` shell
#!/bin/bash

# Set up the example tarfile.
curl -k -o hogan.tar.gz https://registry.npmjs.org/hogan/-/hogan-1.0.5-dev.tgz
rm -f hogan.tar
gunzip hogan.tar.gz

# Clean up from last run.
chmod -R +x out; rm -rf out 
rm -rf node_modules

# Problem!
npm install 'tar@~0.1.12'
node -e '
    var fs = require("fs");
    var tar = require("tar");
    fs.createReadStream("hogan.tar")
        .pipe(tar.Extract({ type: "Directory", path: "out" }));'
```

When I run this, I consistently get an error along the lines of:

```
Error: EACCES, permission denied '[...]/out/package/bin/hulk'
```

which is explained by the fact that the `bin` directory in the tarball isn't set to be searchable. I'd guess that the traditional tar utilities always create searchable directories and then only change permissions after extraction.

I hope this helps!

**Comment by robertgroh** [comment]
As I was recently bitten by this bug and @isaacs asked for a proven solution:
> node-tar should behave the same as gnutar or bsdtar in this respect

I googled a bit and found the description of the behavior of gnutar:

> ### 4.4.2 Changing How tar Writes Files
>
>  #### [Directory Modification Times and Permissions](https://www.gnu.org/software/tar/manual/html_node/Directory-Modification-Times-and-Permissions.html#SEC83)
>
> After successfully extracting a file member, GNU tar normally restores its permissions and modification times, as described in the previous sections. This cannot be done for directories, because after extracting a directory tar will almost certainly extract files into that directory and this will cause the directory modification time to be updated. Moreover, restoring that directory permissions may not permit file creation within it. Thus, restoring directory permissions and modification times must be delayed at least until all files have been extracted into that directory. GNU tar restores directories using the following approach.
>
> The extracted directories are created with the mode specified in the archive, as modified by the umask of the user, which gives sufficient permissions to allow file creation. The meta-information about the directory is recorded in the temporary list of directories. When preparing to extract next archive member, GNU tar checks if the directory prefix of this file contains the remembered directory. If it does not, the program assumes that all files have been extracted into that directory, restores its modification time and permissions and removes its entry from the internal list. This approach allows to correctly restore directory meta-information in the majority of cases, while keeping memory requirements sufficiently small. It is based on the fact, that most tar archives use the predefined order of members: first the directory, then all the files and subdirectories in that directory.
>
> However, this is not always true. ...

Unfortunately I couldn't find such a nice description for bsdtar ([different variants exists] [1]) or [libarchive](http://www.libarchive.org/), but I hope they behave the same.

I hope this description helps to fix this bug.

[1]: http://unix.stackexchange.com/a/104172/117914 "StackExchange Answer listing some variants"

**Comment by isaacs** [comment]
As of v3, node-tar will chmod any folders it creates to make them user-writable.

It doesn't (like gnutar) wait until it's done with the folder, and then try to restore it to not being user-writable.  I believe that non-user-writable/listable folders are almost always a mistake, so we just leave it that way.  This should prevent most of the errors people have encountered with this.

Thanks @robertgroh for the description of how gnutar does it.  We'll consider that if someone has a use case for non-unsable directories.
