### ISSUE TITLE
Fails with ENOENT: no such file or directory, open when filename contains "<"

### ISSUE THREAD

**Issue by AlmirKadric** [npm/node-tar#75]
This module fails to extract files which contain special characters such as `<` however when I use the tar command in cygwin these characters are automatically replaced.

The exact error i get is:

```
{ Error: ENOENT: no such file or directory, open 'C:\path\to\file\containing_<.json'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\path\\to\\file\\containing_<.json' }
```

**Comment by isaacs** [comment]
Looks like we should perhaps be transparently translating between these code points in filenames

```
windows   unix
0xf03c    '<'
0xf03e    '>'
```

But I'm not sure if that belongs in tar, or elsewhere in Node, or if it's a good idea at all.  For example, if an npm package contains a file like `foo<>.js`, then we can translate the filename to `foo\uf03c\uf03e.js`, but if some other module in the package does `require('./foo<>.js')` then it's not going to pick up `foo\uf03c\uf03e.js`.

**Comment by isaacs** [comment]
In the windows command prompt, such a thing looks like this:

```
c:\tar>dir
 Volume in drive C is Windows 10
 Volume Serial Number is 905D-2DA8

 Directory of c:\tar

05/10/2017  11:34 AM    <DIR>          .
05/10/2017  11:34 AM    <DIR>          ..
05/10/2017  11:21 AM                87 .gitignore
05/10/2017  11:21 AM                96 .travis.yml
05/10/2017  11:21 AM    <DIR>          benchmarks
05/10/2017  11:21 AM    <DIR>          lib
05/10/2017  11:21 AM               765 LICENSE
05/10/2017  11:28 AM    <DIR>          node_modules
05/10/2017  11:28 AM            51,927 package-lock.json
05/10/2017  11:21 AM             1,024 package.json
05/10/2017  11:21 AM            31,494 README.md
05/10/2017  11:21 AM    <DIR>          scripts
05/10/2017  11:21 AM               683 tar.js
05/10/2017  11:21 AM    <DIR>          test
05/10/2017  11:33 AM             2,048 wakka.tar
05/10/2017  11:33 AM                 0 _openwaka
05/10/2017  11:33 AM                 0 _closewaka
              10 File(s)         88,124 bytes
               7 Dir(s)  29,616,369,664 bytes free
```

**Comment by AlmirKadric** [comment]
@isaacs when I tested it for one of our games, I extracted assets manually using the cygwin tar command. And served up the files using a node built server. The files seem to be properly served without any filename issues, even though the path was translated. I'm not sure about require and how that behaved though sine we didn't require the files.

Have you tested it using a non-cygwin tar binary (if such a thing exists)? The way I see it, node-tar should behave the same as any other windows tar binary. And I don't think tar should break just because some files have weird names that might not be supported by the target OS.

**Comment by isaacs** [comment]
It looks like mingw tar and cygwin tar do the same thing.

How are you serving the files with node?  When I create a simple node server to serve the files, I see them showing up in teh directory listing like this:

```
ï€¼_openwaka              2017-05-10T18:33:24.000Z           0
ï€¾_closewaka             2017-05-10T18:33:30.000Z           0
```

And when I click the URL, it loads fine, but it looks like this weirdness:

```
http://localhost:1337/%EF%80%BC_openwaka
```

If I try to go to the original filename on the url, it doesn't load:

```
c:\tar>curl "http://localhost:1337/<_openwaka" -i
HTTP/1.1 404 Not Found
content-type: text/plain
Date: Thu, 11 May 2017 17:15:01 GMT
Connection: keep-alive
Content-Length: 10

Not Found
```

**Comment by AlmirKadric** [comment]
I'm not 100% sure, this was over 6 months ago. However we were using express to serve up the assets, it might be doing some OS detection and path translation? Also when testing cygpath, I get the following:
```
$ cygpath -w "helloo>.txt"
helloo.txt
$ cygpath -w "helloo>.txt" | xargs cygpath -u
helloo>.txt
```
As you can see, the path translation is reversible.

Either way since tar on windows seems to behave by translating the paths (cygpath does exactly this for an input path), i do think node-tar should do the same. This just means that if someone wants to properly use these paths they will have to make sure their server properly handles the translation. Right now that option isn't even open as node-tar crashes when other tar applications would just carry on.

If it helps I could write a path translation npm module which could be used by node-tar. This would alleviate some of the work and research from you. Would you be interested in incorporating this if I spend the time to make it?

**Comment by isaacs** [comment]
Sure, a module to do the translation would help a lot.  It should operate entirely in on strings (not talking to filesystem), and have 100% test coverage, and translate all the characters that are problematic on Windows.

It looks like the method for translation is to use the codepoint at `0xf000` plus the code point of the character in question.  So `<` which is 0x3c becomes 0xf03c, and vice versa.

**Comment by isaacs** [comment]
Going from 0x00 to 0xff, the chars that seem to work as expected when translated by adding/removing `0xf000` to the charcode are: `\|<>?:`.

**Comment by isaacs** [comment]
Working as requested on 3.1.2.

Turned out to be pretty easy to just add in this lib, since it's only 2 functions and a simple map.

I don't convert `:` or `\`, since those are legitimately part of a path when it's absolute.

**Comment by AlmirKadric** [comment]
Sweet!!! Thanks for that.
BTW looking at your code, you may have missed a few characters.
Check this list: https://support.microsoft.com/en-us/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names,-folder-names,-and-file-names-in-sharepoint
e.g. the ":" is valid on unix, but not on windows

**Comment by AlmirKadric** [comment]
BTW looking at your code, you may have missed a few characters.
Check this list: https://support.microsoft.com/en-us/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names,-folder-names,-and-file-names-in-sharepoint
e.g. the ":" is valid on unix, but not on windows

**Comment by isaacs** [comment]
@AlmirKadric As mentioned in an earlier comment, `:` and `\` are not converted, because they can be part of a path, so it requires a bit more care to make sure that it behaves properly.

Mingw and cygwin tar don't encode `\`, instead just treating it as a path separator.

`:` can be encoded as `f03a`, but it's a little bit tricky to know that it's not serving as a drive letter separator.  Doable, but less trivial.

**Comment by AlmirKadric** [comment]
Oh sorry, I missed the `:` character in your comment.

This being said, the conversion is done one way at a time. So does `:` in linux translate to a drive separator? isn't that only on windows? in which case can't the ':' be translated to `f03a` when translating from linux to windows?

Or is it a matter of tar not knowing the difference between the 2 operating systems and tries to be agnostic to both? If so could the filename conversion be configurable via a argument? e.g. `-u` assume paths are unix and convert to windows if necessary / `-w` assume paths are windows and convert to unix if necessary. Alternatively for smart pickings, if windows is the only platform that has that drive separator, is it safe to assume a drive letter is only 1 character (https://social.technet.microsoft.com/Forums/windows/en-US/f7079c92-b263-479a-9732-2f0fa4fb862c/drive-letter-after-z?forum=w8itprogeneral)? In which case it will always be the second character. etc.

Sorry for the long dump of thoughts, juts want to make sure the feature is as complete as possible to avoid future issues. Let me know what you think, or if you prefer this to be over and done with.

**Comment by isaacs** [comment]
So, it looks like bsdtar and gnutar both strip `c:\` from path names, on Unix as well as Windows.

Maybe it could do the character swapping after parsing the path name to know whether it's going to strip the drive letter or not?  I'll post an issue as a continuation of this one to capture that additional edge case.
