### ISSUE TITLE
File name too long issue

### ISSUE THREAD

**Issue by yanagiragi** [npm/node-tar#81]
I found that if filename is too long, it may results in filename been cut into specific length and lost file extension. I've tried cut filename so that it's length <= 100 (Standard of GNU tar), but problem still remains.

Thank you.

**Comment by isaacs** [comment]
Long filenames work fine on v3.  How are you unpacking the tarball?

**Comment by yanagiragi** [comment]
It would be fine if I use native tar (tar -cvf in FreeBSD), However since time passes, I may not able to have exactly same enviornment for testing :(
So I use native tar after some tries, it works fine for now.

**Comment by RVisionAutomerge** [comment]
Seems like regress in 4.x version.
Name
`very long file name a s dd f df  sdfsdfsdfsdfsdffffffff~fffffsdddddddddddddddddddddddddddssssssssssssssssss.xml`
Is truncated to
`very long file name a s dd f df  sdfsdfsdfsdfsdfffffffffffffffffffffffffffffffffffsdddddddddddddddd`

**Comment by Dzenly** [comment]
Seems like regress in 4.x version (4.4.10).
Name
very long file name a s dd f df sdfsdfsdfsdfsdffffffff~fffffsdddddddddddddddddddddddddddssssssssssssssssss.xml
Is truncated to
very long file name a s dd f df sdfsdfsdfsdfsdfffffffffffffffffffffffffffffffffffsdddddddddddddddd
