### ISSUE TITLE
@filename.tar as file entry to copy from one tarball to another

### ISSUE THREAD

**Issue by isaacs** [npm/node-tar#94]
This is a very optional thing, and I'm not sure how useful it really is, but the completionist in me wants to do it.

If you do `tar cf new.tar @old.tar` it'll take the entries in `old.tar` and re-encode them as new entries in `new.tar`.  (You can also do this with `u` and `r`.)

It might require refactoring how `write-entry.js` works, because right now it takes a path, or maybe there needs to be a `tar-entry.js` that takes a `ReadEntry` and turns it directly into a `WriteEntry`.

**Comment by isaacs** [comment]
YAGNI.  Closing until someone has a need for this.  It's a very obscure feature.

**Comment by matthiasg** [comment]
This sounds very interesting, I currently need to combine two tgz files and cannot quite find out how to pipe from a readstream to a tar writestream. This sounds helpful

**Comment by isaacs** [comment]
Note: this did end up landing eventually.  You can do `tar.c({file:'combined.tar'}, ['@one.tar', '@two.tar'])` and it'll combine them into one.

**Comment by matthiasg** [comment]
@isaacs thanks. I assume this will also work with tgz files. I will try that. I missed the '@' special syntax
